/* All UI words, English and Bengali. Strings may contain {placeholders}; some contain trusted inline HTML. */

const en = {
  brand: "South Pole Window",
  nav: { home: "Overview", planner: "Planner", game: "Race the Shadow" },
  theme: { toLight: "Switch to light theme", toDark: "Switch to dark theme" },
  loading: "Loading the JPL ephemeris…",
  loadFail: "Couldn't load the sky data. Reload the page to try again.",
  footer: "Sun and Earth positions: NASA JPL DE421 ephemeris with lunar librations · Moon ME frame · all times UTC · Built for NASA Space Apps 2026, CLPS Lunar Mission Browser",
  compass: ["N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"],
  utc: "UTC",
  sun: "Sun", earth: "Earth",
  days: "{n} days", day1: "1 day", hours: "{n} hours", hour1: "1 hour", zero: "none",

  l: {
    kicker: "Live · NASA JPL DE421 ephemeris",
    title: "Chase the <em>light</em> at the bottom of the Moon.",
    lede: "At the lunar south pole the Sun never climbs more than a degree or two. It circles the horizon and drags shadows tens of kilometres long across the crater rims. Pick where and when to land, and see exactly when a lander has power and a line home.",
    ctaPlanner: "Open the Planner", ctaGame: "Play Race the Shadow",
    f1: "tilt of the Moon\u2019s axis", f2: "one sunrise to the next", f3: "Earth\u2019s wobble in the sky",
    sunAtPole: "Sun above the pole", sitesLit: "Sites in sunlight", speed: "{n} d/s",
    terrainNote: "Relief is illustrative. Sun and Earth directions are real for the time shown. Drag to scrub.",
    liveKicker: "Right now on the Moon", liveTitle: "{n} of {total} sites have power and a line to Earth",
    sunUp: "Sun up", sunDown: "Sun down", earthUp: "Earth in view", earthDown: "Earth hidden", details: "Details",
    needKicker: "The problem", needTitle: "A south-pole lander needs two things at once",
    powerTag: "Power", powerTitle: "Sunlight on the panels",
    powerText: "The Sun skims the horizon, so a hill a few kilometres away can hide it for days. Nights on crater floors last weeks; high rims can stay lit for most of a year.",
    linkTag: "Link", linkTitle: "Earth above the horizon",
    linkText: "Earth hangs low in the sky from the pole and slowly bobs up and down as the Moon wobbles. When it dips below the skyline, the lander can\u2019t call home without a relay.",
    toolKicker: "The Planner", toolTitle: "Everything a mission planner needs, in one screen",
    next30: "Next 30 days · {site}",
    tools: {
      compare: { t: "Compare sites side by side", d: "Sunlight, longest night, Earth visibility and time with both, for every candidate on the same dates." },
      scrub: { t: "Stand on the site and press Play", d: "A 360° skyline with the Sun and Earth moving across it, hour by hour." },
      windows: { t: "Find the best time to land", d: "Every 6 hours is tested as a touchdown; the top windows are ranked by power and signal together." },
      terrain: { t: "Bring real LOLA terrain", d: "Load a horizon mask made from NASA elevation maps and every number updates to the true skyline." },
    },
    gameKicker: "For classrooms and the curious", gameTitle: "Race the Shadow",
    gameText: "Keep a small lander alive through the lunar night. Every sunrise and Earth-set in the game comes from the same real ephemeris.",
    apiKicker: "For developers", apiTitle: "The same numbers, as JSON",
    apiText: "Every page here is computed on the server from the DE421 table. Query any site, or any latitude and longitude.",
  },
  s: {
    back: "Overview", kicker: "Landing site", open: "Open in the Planner", pub: "{p}% lit long-term in terrain studies",
    now: "Right now", monthKicker: "Next 30 days", monthTitle: "Sun and Earth above the horizon",
    eventsTitle: "Coming up", noEvents: "No sunrises, sunsets, Earth-rises or Earth-sets in the next 30 days.",
    yearTitle: "The next 12 months", others: "Other sites",
    ev: { sunrise: "Sunrise", sunset: "Sunset", earthrise: "Earth rises", earthset: "Earth sets" },
  },
  p2: {
    title: "Plan a landing",
    intro: "Pick a site and dates. See when a lander gets sunlight for power and can see Earth to send data home.",
    s1: "Pick a landing site", s1h: "Click a dot on the map or a name in the list.",
    listHead: "Power + signal",
    s2: "Pick the dates", s2h: "When would the lander be there?",
    s3: "Result",
    vGreat: "Good for landing", vOk: "Workable with planning", vHard: "Risky",
    bodyGreat: "Plenty of sunlight and regular contact with Earth.",
    bodyOk: "Expect breaks in power or radio contact.",
    bodyHard: "Long dark periods or little contact with Earth.",
    warn: "Nights last more than 4 days here. Most small landers freeze.",
    cSun: "Sunlight", cDark: "Longest night", cEarth: "Earth in view", cBoth: "Power + signal",
    skyT: "Look around the site", skyH: "Press Play to watch the Sun and Earth move across the sky. Grey is the ground.",
    tlT: "The whole period at a glance", tlH: "Above 0° means visible. The bars show power, signal, or both. Drag to move in time.",
    cmpT: "Compare all sites", cmpH: "Same dates for every site. Click a row to switch.",
    winT: "Best times to land", winH: "Top start times for a {n}-day mission.",
    winGap: "longest break: {d}",
    more: "Learn more: words and methods",
    pubTip: "Long-term sunlight from studies that include real mountains",
  },
  l2: {
    lede: "The Sun barely rises at the Moon\u2019s south pole. Find where and when a lander gets sunlight and can see Earth.",
    liveT: "Right now on the Moon", liveH: "Live from NASA JPL data. A site is ready when it has sunlight and a view of Earth.",
    colSite: "Site", colSun: "Sunlight", colEarth: "Earth", colStatus: "Status",
    ready: "Ready", noPower: "No power", noSignal: "No signal", offline: "Dark and silent",
    up: "Up", down: "Down", visible: "Visible", hidden: "Hidden",
    whyT: "Why it\u2019s hard", whyH: "A lander needs both of these at the same time.",
    powerT: "Sunlight for power", powerD: "The Sun skims the horizon, so a nearby hill can hide it for days.",
    linkT: "Earth in view for radio", linkD: "Earth sits low in the sky and slowly bobs below the horizon.",
    howT: "How to plan a landing", howH: "Three steps in the Planner.",
    h1: "Pick a site", h1d: "Click a spot on the polar map.",
    h2: "Pick dates", h2d: "Choose when the lander arrives.",
    h3: "Read the result", h3d: "See power, signal and the best landing times.",
    gameT: "Learn by playing", gameD: "Keep a lander alive through the lunar night, on the same real sky data.",
    api: "Developers: JSON API",
  },
  s2: {
    monthH: "Above 0° means visible from the site.",
    yearT: "Next 12 months", yearH: "Share of the year with sunlight, Earth, and both.",
    eventsH: "Next sunrises, sunsets and Earth-sets (UTC).",
  },
  g2: { intro: "Keep a small lander alive near the Moon\u2019s south pole. The Sun charges it, the cold drains it, and it can only send data while Earth is up." },
  w: {
    title: "Why it\u2019s hard",
    help: "Same Sun, same Earth. Only where the lander stands changes. Switch places and watch one Moon day.",
    canvasLabel: "A lander on the lunar south pole with the Sun and Earth moving along the horizon",
    where: "Where the lander stands", ridge: "On a ridge", crater: "In a crater",
    pOn: "Power on", pOff: "No power", rOn: "Radio on", rOff: "No radio",
    msgBoth: "Sunlight and Earth in view: the lander can work.",
    msgNoSun: "The Sun is behind the skyline: no power, the lander freezes.",
    msgNoEarth: "Earth has dropped below the skyline: no radio contact.",
    msgNone: "No Sun and no Earth: the lander must sleep and wait.",
    day: "Moon day \u00b7 day {d} of 30",
    tally: "Over this Moon day",
    tPower: "power", tRadio: "radio",
    note: "Real Sun and Earth positions from NASA JPL for the coming Moon day. Skylines are illustrative; heights are exaggerated \u00d7{k}.",
    photoT: "The real south pole, from orbit",
    photoD: "This is an actual photo mosaic from NASA\u2019s Lunar Reconnaissance Orbiter. The pole is at the centre. Black patches are crater floors the Sun never reaches; bright rims catch light for most of the year. That contrast is exactly what a mission has to plan around.",
    photoPin: "Shackleton crater (the pole)",
    photoDark: "Always in shadow",
    photoCredit: "Image: NASA/GSFC/Arizona State University, LROC WAC south pole mosaic",
  },
  p: {
    kicker: "NASA Space Apps 2026 · CLPS Lunar Mission Browser",
    question: 'Where and when can a lander near the Moon’s south pole get <b>sunlight for power</b> and <em>see Earth to talk home</em>?',
    step1: "Pick a site on the polar map", step2: "Choose the dates", step3: "Read the verdict and press Play",
    setup: "Mission setup",
    mapTitle: "South polar map",
    mapSub: "Looking down on the pole. Each ring fills with the share of time a site has power and signal together.",
    mapEarth: "toward Earth", mapSunNow: "Sun direction now",
    dropPin: "Drop a pin", dropHint: "Click the map to add a site there", cancel: "Cancel",
    offMap: "off map",
    pickSite: "Landing site", pickDates: "Dates", startDate: "Start date", howLong: "How long",
    opt14: "2 weeks", opt29: "1 Moon day (29.5 days)", opt60: "2 months", opt180: "6 months", opt365: "1 year",
    dateHint: "One Moon day lasts about 29.5 Earth days. At the pole, seasons also change how much sunlight reaches the ground over the year.",
    advanced: "Advanced settings", missionLen: "Mission length (days)", missionHint: "Used to rank the best days to land.",
    maskLbl: "Earth must be at least this high (°)", maskHint: "Antennas often need Earth a few degrees above the horizon. 0 means just above it.",
    horizonLbl: "Ground shape around the site", hSmooth: "Smooth Moon (no mountains)", hRaised: "Site on a hill (enter height)", hTerrain: "Real terrain from NASA LOLA (load file)",
    metres: "metres above the plains", loadCsv: "Load a terrain file (CSV from horizon_mask.py)",
    csvBad: "Couldn't read a horizon from that file. Expected lines of azimuth_deg,horizon_deg.",
    csvFar: "Loaded, but this file was made for {lat}, {lon}, not {site}.",
    addSite: "Add a site by coordinates", latlonHint: "Latitude, longitude in degrees. South is negative, west is negative.", addBtn: "Add site", custom: "My site",
    ground: "Ground and mountains", sky: "sky",
    skyTitle: "What you'd see standing there",
    skySub: "A full turn around you, north back to north. The grey shape is the ground; anything above it is visible. Faint dots trace the Sun and Earth over the whole period.",
    hSmoothS: "smooth Moon", hRaisedS: "on a {h} m hill", hTerrainS: "real terrain",
    play: "Play", pause: "Pause", speed: "Speed", time: "Time",
    sunUp: "Sun is up", sunUpN: "solar panels are charging", sunPart: "Sun is partly hidden", sunPartN: "{p}% of the Sun is visible", sunDown: "Sun is down", sunDownN: "running on batteries",
    earthUp: "Earth is visible", earthUpN: "can send data home", earthDown: "Earth is hidden", earthDownN: "no signal to Earth",
    tlTitle: "Over the whole period",
    tlSub: "Lines above zero mean the Sun or Earth is visible. The bars below show when the lander has power, a signal, or both. Click or drag to move through time.",
    yAxis: "degrees above horizon", bPower: "Power", bSignal: "Signal", bBoth: "Both",
    cmpTitle: "Compare landing sites", cmpSub: "Same dates for every site. Click a row to open it, click a heading to sort.",
    cSite: "Site", cSun: "Sunlight", cDark: "Longest dark", cEarth: "Earth in view", cBoth: "Both", cPub: "Published",
    pubHint: '“Published” is a long-term sunlight figure from studies that include real mountains (<a href="https://en.wikipedia.org/wiki/Peak_of_eternal_light" target="_blank" rel="noopener">summary</a>). A big gap from our smooth-Moon number shows how much the terrain matters.',
    winTitle: "Best times to land",
    winSub: "For a {n}-day mission at {site}. Higher % means more time with power and a signal at the same time.",
    winWorst: "longest time without both: {d}", winSc: "power + signal",
    winNone: "No landing time in these dates has the Sun and Earth up together here. Try longer dates, another site, or lower the Earth height in Advanced settings.",
    kSun: "Sunlight (power)", kSunN: "of the time", kDark: "Longest dark stretch", kDarkN0: "Sun never sets", kDarkN: "in one go",
    kEarth: "Earth in view (signal)", kEarthN: "of the time", kBoth: "Power and signal together", kBothN: "of the time",
    vGreat: "Good place to land", vOk: "Possible, with planning", vHard: "Hard place to survive",
    vHeadGreat: "{site} looks good for these dates", vHeadOk: "{site} can work, but plan for gaps", vHeadHard: "{site} is tough for these dates",
    vSunAll: "The Sun never sets here in this period, so the solar panels always get light.",
    vSun: "The Sun is up {p}% of the time. The longest stretch of darkness is {d}.",
    vEarthAll: "Earth is always in view, so the lander can always send data home.",
    vEarthNone: "Earth never rises here in this period, so the lander can't talk home directly. It would need a relay satellite.",
    vEarth: "Earth is visible {p}% of the time, so the lander can talk home that often. The longest silence is {d}.",
    vWarn: "Warning: most small landers can't survive more than a few days without sunlight. The cold drains the batteries.",
    vTerrain: "This uses a smooth Moon with no mountains. Load real terrain in Advanced settings for a site-specific answer.",
    glossTitle: "Words used here",
    gloss: [["Horizon", "The line where the ground meets the sky. Mountains and crater rims make it higher in some directions."],
            ["Elevation", "How high something is above the flat horizon, in degrees. 0° is right on the horizon, 90° is straight up."],
            ["Direct-to-Earth link", "The lander talking to Earth by radio. It only works when Earth is above the horizon."],
            ["Moon day", "About 29.5 Earth days from one sunrise to the next. Away from the poles, that's roughly 2 weeks of light and 2 weeks of night."],
            ["Why the pole is special", "The Moon's axis is tilted only 1.5°, so at the pole the Sun circles around the horizon instead of rising high."],
            ["Libration", "The Moon wobbles slightly as it orbits, so from the pole Earth slowly bobs above and below the horizon."],
            ["LOLA", "A laser on NASA's Lunar Reconnaissance Orbiter that mapped the height of the whole Moon."],
            ["CLPS", "Commercial Lunar Payload Services: NASA pays companies to fly science to the Moon on their landers."]],
    howTitle: "How the numbers are calculated",
    notes: ["<b>Where the Sun and Earth are.</b> From NASA JPL's DE421 ephemeris, including the Moon's wobble (librations), turned into the Moon-fixed frame used by NASA's LOLA maps. Light travel time and the site's offset from the Moon's centre are included. The data covers 2026–2032 at 3-hour steps. The Moon orientation agrees with the independent IAU model to within 15 arcseconds.",
            "<b>Power.</b> Counted when at least half of the Sun's disk is above the horizon in the Sun's direction.",
            "<b>Signal.</b> Counted when Earth's centre is above the horizon plus the minimum height set in Advanced settings.",
            "<b>Ground shape.</b> Smooth Moon uses a perfect sphere. Site on a hill lowers the horizon the way it would for a peak above flat plains. Real terrain uses a skyline computed from NASA LOLA elevation maps with the included Python tool. Only real terrain captures shadows from crater rims.",
            "<b>Best times to land.</b> Every 6 hours in the chosen dates is tested as a landing time. The score is the share of the mission with power and signal together; ties go to the shorter worst gap. Landing needs the Sun and Earth both up.",
            "<b>Limits.</b> Site coordinates come from published studies and are approximate. Relay satellites, ground-station schedules, temperature and slope safety are not included."],
    gameCta: "Play Race the Shadow", gameCtaSub: "Keep a lander alive through the lunar night, on the same sky data.",
  },

  g: {
    tagline: "A lunar survival game running on real NASA JPL sky data",
    intro: "You run a small robotic lander near the Moon's south pole. <b>The Sun charges your battery, the cold drains it, and you can only send science home when Earth is above the horizon.</b> Every sunrise, sunset and Earth-set in this game comes from NASA JPL's real ephemeris for the dates you play.",
    scn: {
      vikram: { t: "Vikram's Night", d: "Hard", story: "In 2023, India's Vikram lander touched down near 69°S, did its science, and never woke up after its first lunar night. Your lander has survival heaters. Can it live through the dark?", goal: "Survive the 2-week night and wake up at sunrise." },
      tipped: { t: "Tipped Over", d: "Medium", story: "In 2025, a lander touched down on its side and its solar panels pointed the wrong way. Yours has landed crooked on Malapert Mountain. The panel only catches the Sun from one direction.", goal: "Send {g} MB of science home in 10 days." },
      peak: { t: "Peak of Light", d: "Open", story: "Be the mission planner. Pick a site on the south-pole ridges and a landing date anywhere in the next year, then fly a 14-day mission.", goal: "Send as much science home as you can in 14 days." },
    },
    best: "Your best: {v}", play: "Play",
    howto: [["Science", "Collects data but uses power."], ["Radio", "Sends data home, only while Earth is up."], ["Hibernate", "Shuts almost everything off to survive the dark."], ["Forecast", "Shows when the Sun and Earth will be up. Plan ahead."]],
    setupTitle: "Choose where and when to land", setupSub: "Real planners do exactly this. The forecast below shows the next 14 days of sunlight and Earth contact for your choice.",
    site: "Landing site", landDate: "Landing date (00:00 UTC)", back: "Back", launch: "Land here",
    pvTxt: "Next 14 days: Sun up {s}% of the time, Earth up {e}%, both together {b}%.",
    abort: "Quit mission", battery: "Battery", stored: "Science waiting", sent: "Sent to Earth", clock: "Mission time",
    fcTitle: "Forecast: next 5 days", fcSub: "from the real ephemeris", now: "now", dayN: "+{n}d",
    sci: "Science instruments", rad: "Radio to Earth", hib: "Hibernate", on: "ON", off: "OFF",
    sciS: "+{mb} MB/h · uses {w} W", radS: "{mb} MB/h · {w} W · needs Earth up", hibS: "Uses only {w} W. Science and radio stop.",
    radWait: "Waiting: Earth is below the horizon", radIdle: "Nothing to send yet",
    autoPause: "Pause on alerts", logTitle: "Mission log", pauseLbl: "Pause", spaceHint: "Space bar pauses and resumes",
    flowIn: "Solar in", flowOut: "Using", maxMb: "max {n} MB",
    day: "Day {d}", dayShort: "Day {d} · {h}:00",
    goal: "Goal", goalPeak: "send as much as you can in 14 days",
    exag: "heights exaggerated ×{k}", panel: "panel",
    ev: {
      land: "Touchdown! Systems are online.",
      sunsetSoon: "Sunset in about {h} hours. Is your battery full?",
      sunset: "The Sun has set. Heaters are on.",
      sunrise: "Sunrise! The panels are charging again.",
      earthsetSoon: "Earth sets in about {h} hours. Send your data now.",
      earthset: "Earth has set. No radio contact.",
      earthrise: "Earth is back above the horizon.",
      batLow: "Battery below 25%. Cut power or hibernate.",
      storeFull: "Memory full. New science is being lost.",
      frozen: "Battery empty. The lander froze.",
      done: "Mission complete.", hib: "Hibernating. Only survival heaters are on.", wake: "Waking up. Systems back online.",
    },
    win: "Mission success", lose: "Lander lost", done: "Mission complete",
    st: { sent: "Sent to Earth", lost: "Science lost (memory full)", minBat: "Lowest battery", dark: "Hours in darkness", survived: "Survived", hours: "{n} h" },
    replayCap: "Battery over the mission (amber = Sun up, blue = Earth up).",
    again: "Try again", other: "Other missions",
    why: {
      title: "Why did that happen?",
      vikramWin: "You entered the night with <b>{b}%</b> battery and hibernated. At {w} W, the survival heaters needed about <b>{need} Wh</b> to get through <b>{n} hours</b> of darkness.",
      vikramLose: "The night at this site lasted <b>{n} hours</b>. Awake, the lander uses {aw} W in the dark, so a full battery lasts only about <b>{last} hours</b>. Even hibernating, it needs about {need} Wh, so it must start the night nearly full.",
      vikramFact: "The real Vikram lander was designed for one lunar day, about 14 Earth days, and did not wake up after the night. Surviving the lunar night is one of the hardest problems for Moon landers.",
      tippedTxt: "Your panel faced {pa}°. Near the pole the Sun circles the whole horizon about once every 29.5 days, so it spent part of the mission behind your panel. Power came mostly when the Sun swung around toward it.",
      tippedLose: "Your lander ran everything while the panel was getting little or no light, and the battery emptied. Hibernate at first, and turn science on once the Sun swings round toward the panel.",
      tippedFact: "When a lander tips over, the solar panels can end up facing the ground or the wrong direction, and the mission may end early because the batteries can't recharge.",
      peakTxt: "At {site}, the Sun was up {s}% and Earth {e}% of your mission, both together {b}%. Sites high on crater rims and ridges catch more sunlight; Earth contact depends on the Moon's slow wobble.",
      peakFact: "Try the same site on a different date, or compare every site at once in the Planner.",
      data: "All Sun and Earth positions came from NASA JPL's DE421 ephemeris for your exact dates. The Moon is treated as smooth (no mountains), so real rim sites may do even better.",
      open: "Open this site in the Planner",
    },
  },
};

type Dict = typeof en;

const bn: Dict = {
  brand: "দক্ষিণ মেরু উইন্ডো",
  nav: { home: "সারসংক্ষেপ", planner: "প্ল্যানার", game: "ছায়ার সাথে দৌড়" },
  theme: { toLight: "হালকা থিমে যাও", toDark: "গাঢ় থিমে যাও" },
  loading: "JPL ephemeris লোড হচ্ছে…",
  loadFail: "আকাশের ডেটা লোড হয়নি। আবার চেষ্টা করতে পেজটা রিলোড করো।",
  footer: "সূর্য আর পৃথিবীর অবস্থান: NASA JPL DE421 ephemeris, চাঁদের দোলন সহ · চাঁদের ME ফ্রেম · সব সময় UTC-তে · NASA Space Apps 2026, CLPS Lunar Mission Browser চ্যালেঞ্জের জন্য তৈরি",
  compass: ["N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"],
  utc: "UTC",
  sun: "সূর্য", earth: "পৃথিবী",
  days: "{n} দিন", day1: "১ দিন", hours: "{n} ঘণ্টা", hour1: "১ ঘণ্টা", zero: "নেই",

  l: {
    kicker: "লাইভ · NASA JPL DE421 ephemeris",
    title: "চাঁদের একদম নিচে <em>আলোর</em> পিছু নাও।",
    lede: "চাঁদের দক্ষিণ মেরুতে সূর্য কখনো এক-দুই ডিগ্রির বেশি ওঠে না। সে দিগন্ত ঘিরে ঘোরে আর গর্তের কিনারায় কয়েক দশ কিলোমিটার লম্বা ছায়া টেনে নেয়। কোথায় আর কবে নামবে বেছে নাও, আর দেখো ঠিক কখন ল্যান্ডার বিদ্যুৎ পাবে আর বাড়ির সাথে যোগাযোগ রাখতে পারবে।",
    ctaPlanner: "প্ল্যানার খোলো", ctaGame: "ছায়ার সাথে দৌড় খেলো",
    f1: "চাঁদের অক্ষের হেলানো", f2: "এক সূর্যোদয় থেকে পরেরটা", f3: "আকাশে পৃথিবীর দোলন",
    sunAtPole: "মেরুর উপরে সূর্য", sitesLit: "আলোয় থাকা সাইট", speed: "{n} দিন/সে",
    terrainNote: "ভূখণ্ড আনুমানিক। দেখানো সময়ের সূর্য আর পৃথিবীর দিক আসল। সময় বদলাতে টেনে নাও।",
    liveKicker: "এই মুহূর্তে চাঁদে", liveTitle: "{total}টার মধ্যে {n}টা সাইটে বিদ্যুৎ আর পৃথিবীর সাথে যোগাযোগ আছে",
    sunUp: "সূর্য উঠে আছে", sunDown: "সূর্য ডুবে আছে", earthUp: "পৃথিবী দেখা যায়", earthDown: "পৃথিবী আড়ালে", details: "বিস্তারিত",
    needKicker: "সমস্যাটা", needTitle: "মেরুর ল্যান্ডারের একসাথে দুটো জিনিস লাগে",
    powerTag: "বিদ্যুৎ", powerTitle: "প্যানেলে সূর্যের আলো",
    powerText: "সূর্য দিগন্ত ছুঁয়ে যায়, তাই কয়েক কিলোমিটার দূরের একটা পাহাড়ও তাকে দিনের পর দিন ঢেকে রাখতে পারে। গর্তের তলায় রাত কয়েক সপ্তাহ; উঁচু কিনারা বছরের বেশিরভাগ সময় আলোয় থাকতে পারে।",
    linkTag: "যোগাযোগ", linkTitle: "দিগন্তের উপরে পৃথিবী",
    linkText: "মেরু থেকে পৃথিবী আকাশে নিচু হয়ে থাকে আর চাঁদের দোলনে ধীরে ধীরে ওঠানামা করে। দিগন্তের নিচে নামলে রিলে ছাড়া ল্যান্ডার বাড়িতে কথা বলতে পারে না।",
    toolKicker: "প্ল্যানার", toolTitle: "মিশন প্ল্যানারের যা লাগে, সব এক পর্দায়",
    next30: "পরের ৩০ দিন · {site}",
    tools: {
      compare: { t: "সাইট পাশাপাশি তুলনা", d: "একই তারিখে প্রতিটা সাইটের সূর্যের আলো, লম্বা রাত, পৃথিবী দেখা আর দুটো একসাথে থাকার সময়।" },
      scrub: { t: "সাইটে দাঁড়িয়ে Play চাপো", d: "৩৬০° দিগন্তে ঘণ্টায় ঘণ্টায় সূর্য আর পৃথিবীর চলাচল।" },
      windows: { t: "নামার সেরা সময় খোঁজো", d: "প্রতি ৬ ঘণ্টা নামার সময় হিসেবে পরীক্ষা হয়; বিদ্যুৎ আর সিগন্যাল একসাথে ধরে সেরাগুলো সাজানো।" },
      terrain: { t: "আসল LOLA ভূখণ্ড আনো", d: "NASA উচ্চতার ম্যাপ থেকে বানানো দিগন্ত লোড করো, সব সংখ্যা আসল দিগন্ত ধরে বদলে যাবে।" },
    },
    gameKicker: "ক্লাসরুম আর কৌতূহলীদের জন্য", gameTitle: "ছায়ার সাথে দৌড়",
    gameText: "চন্দ্র-রাত পার করে একটা ছোট ল্যান্ডার বাঁচিয়ে রাখো। গেমের প্রতিটা সূর্যোদয় আর পৃথিবী-অস্ত একই আসল ephemeris থেকে।",
    apiKicker: "ডেভেলপারদের জন্য", apiTitle: "একই সংখ্যা, JSON হিসেবে",
    apiText: "এখানকার প্রতিটা পেজ সার্ভারে DE421 টেবিল থেকে হিসাব করা। যেকোনো সাইট বা অক্ষাংশ-দ্রাঘিমাংশ জিজ্ঞেস করো।",
  },
  s: {
    back: "সারসংক্ষেপ", kicker: "ল্যান্ডিং সাইট", open: "প্ল্যানারে খোলো", pub: "ভূখণ্ড-গবেষণায় দীর্ঘমেয়াদে {p}% আলো",
    now: "এই মুহূর্তে", monthKicker: "পরের ৩০ দিন", monthTitle: "দিগন্তের উপরে সূর্য আর পৃথিবী",
    eventsTitle: "সামনে যা আসছে", noEvents: "পরের ৩০ দিনে কোনো সূর্যোদয়, সূর্যাস্ত, পৃথিবী-উদয় বা পৃথিবী-অস্ত নেই।",
    yearTitle: "পরের ১২ মাস", others: "অন্য সাইট",
    ev: { sunrise: "সূর্যোদয়", sunset: "সূর্যাস্ত", earthrise: "পৃথিবী ওঠে", earthset: "পৃথিবী ডোবে" },
  },
  p2: {
    title: "অবতরণের পরিকল্পনা",
    intro: "সাইট আর তারিখ বেছে নাও। দেখো কখন ল্যান্ডার বিদ্যুতের জন্য সূর্যের আলো পায় আর ডেটা পাঠাতে পৃথিবী দেখতে পায়।",
    s1: "ল্যান্ডিং সাইট বেছে নাও", s1h: "মানচিত্রের বিন্দুতে বা তালিকার নামে চাপো।",
    listHead: "বিদ্যুৎ + সিগন্যাল",
    s2: "তারিখ বেছে নাও", s2h: "ল্যান্ডার কখন সেখানে থাকবে?",
    s3: "ফলাফল",
    vGreat: "নামার জন্য ভালো", vOk: "পরিকল্পনা করলে চলবে", vHard: "ঝুঁকিপূর্ণ",
    bodyGreat: "প্রচুর সূর্যের আলো আর পৃথিবীর সাথে নিয়মিত যোগাযোগ।",
    bodyOk: "বিদ্যুৎ বা রেডিও যোগাযোগে বিরতি আশা করো।",
    bodyHard: "লম্বা অন্ধকার সময় বা পৃথিবীর সাথে খুব কম যোগাযোগ।",
    warn: "এখানে রাত ৪ দিনের বেশি। বেশিরভাগ ছোট ল্যান্ডার জমে যায়।",
    cSun: "সূর্যের আলো", cDark: "সবচেয়ে লম্বা রাত", cEarth: "পৃথিবী দেখা যায়", cBoth: "বিদ্যুৎ + সিগন্যাল",
    skyT: "সাইটের চারপাশ দেখো", skyH: "Play চাপো, আকাশে সূর্য আর পৃথিবীর চলাচল দেখো। ধূসর অংশটা মাটি।",
    tlT: "পুরো সময় এক নজরে", tlH: "০° এর উপরে মানে দেখা যায়। বারগুলো বিদ্যুৎ, সিগন্যাল বা দুটোই দেখায়। সময় বদলাতে টেনে নাও।",
    cmpT: "সব সাইট তুলনা", cmpH: "সব সাইটের জন্য একই তারিখ। বদলাতে কোনো সারিতে চাপো।",
    winT: "নামার সেরা সময়", winH: "{n} দিনের মিশনের জন্য সেরা শুরুর সময়।",
    winGap: "সবচেয়ে লম্বা বিরতি: {d}",
    more: "আরও জানো: শব্দ আর পদ্ধতি",
    pubTip: "আসল পাহাড়-পর্বত ধরে করা গবেষণায় দীর্ঘমেয়াদি আলো",
  },
  l2: {
    lede: "চাঁদের দক্ষিণ মেরুতে সূর্য প্রায় ওঠেই না। খুঁজে বের করো কোথায় আর কবে ল্যান্ডার আলো পায় আর পৃথিবী দেখতে পায়।",
    liveT: "এই মুহূর্তে চাঁদে", liveH: "NASA JPL ডেটা থেকে লাইভ। সূর্যের আলো আর পৃথিবী দুটোই থাকলে সাইট প্রস্তুত।",
    colSite: "সাইট", colSun: "সূর্যের আলো", colEarth: "পৃথিবী", colStatus: "অবস্থা",
    ready: "প্রস্তুত", noPower: "বিদ্যুৎ নেই", noSignal: "সিগন্যাল নেই", offline: "অন্ধকার আর নীরব",
    up: "উঠে আছে", down: "ডুবে আছে", visible: "দেখা যায়", hidden: "আড়ালে",
    whyT: "কেন কঠিন", whyH: "ল্যান্ডারের একই সময়ে এই দুটো লাগে।",
    powerT: "বিদ্যুতের জন্য সূর্যের আলো", powerD: "সূর্য দিগন্ত ছুঁয়ে যায়, তাই কাছের একটা পাহাড় দিনের পর দিন তাকে ঢেকে রাখতে পারে।",
    linkT: "রেডিওর জন্য পৃথিবী দেখা", linkD: "পৃথিবী আকাশে নিচু থাকে আর ধীরে ধীরে দিগন্তের নিচে নামে-ওঠে।",
    howT: "কীভাবে অবতরণ পরিকল্পনা করবে", howH: "প্ল্যানারে তিনটা ধাপ।",
    h1: "সাইট বেছে নাও", h1d: "মেরুর মানচিত্রে একটা জায়গায় চাপো।",
    h2: "তারিখ বেছে নাও", h2d: "ল্যান্ডার কবে পৌঁছাবে ঠিক করো।",
    h3: "ফলাফল পড়ো", h3d: "বিদ্যুৎ, সিগন্যাল আর নামার সেরা সময় দেখো।",
    gameT: "খেলে শেখো", gameD: "একই আসল আকাশের ডেটায় চন্দ্র-রাত পার করে ল্যান্ডার বাঁচিয়ে রাখো।",
    api: "ডেভেলপারদের জন্য: JSON API",
  },
  s2: {
    monthH: "০° এর উপরে মানে সাইট থেকে দেখা যায়।",
    yearT: "পরের ১২ মাস", yearH: "বছরের কত অংশে সূর্যের আলো, পৃথিবী, আর দুটোই।",
    eventsH: "পরের সূর্যোদয়, সূর্যাস্ত আর পৃথিবী-অস্ত (UTC)।",
  },
  g2: { intro: "চাঁদের দক্ষিণ মেরুর কাছে একটা ছোট ল্যান্ডার বাঁচিয়ে রাখো। সূর্য চার্জ দেয়, ঠান্ডা ব্যাটারি খরচ করে, আর পৃথিবী উপরে থাকলেই কেবল ডেটা পাঠানো যায়।" },
  w: {
    title: "কেন কঠিন",
    help: "একই সূর্য, একই পৃথিবী। শুধু ল্যান্ডার কোথায় দাঁড়িয়ে আছে সেটা বদলায়। জায়গা বদলে চাঁদের একটা দিন দেখো।",
    canvasLabel: "চাঁদের দক্ষিণ মেরুতে একটা ল্যান্ডার, দিগন্ত ধরে সূর্য আর পৃথিবী চলছে",
    where: "ল্যান্ডার কোথায় দাঁড়িয়ে", ridge: "শৈলশিরার উপরে", crater: "গর্তের ভেতরে",
    pOn: "বিদ্যুৎ আছে", pOff: "বিদ্যুৎ নেই", rOn: "রেডিও চালু", rOff: "রেডিও নেই",
    msgBoth: "সূর্যের আলো আর পৃথিবী দুটোই আছে: ল্যান্ডার কাজ করতে পারবে।",
    msgNoSun: "সূর্য দিগন্তের পেছনে: বিদ্যুৎ নেই, ল্যান্ডার জমে যাচ্ছে।",
    msgNoEarth: "পৃথিবী দিগন্তের নিচে নেমে গেছে: রেডিও যোগাযোগ নেই।",
    msgNone: "সূর্যও নেই, পৃথিবীও নেই: ল্যান্ডারকে ঘুমিয়ে অপেক্ষা করতে হবে।",
    day: "চাঁদের দিন \u00b7 ৩০ এর মধ্যে {d} নম্বর দিন",
    tally: "এই চাঁদের দিন জুড়ে",
    tPower: "বিদ্যুৎ", tRadio: "রেডিও",
    note: "সামনের চাঁদের দিনের জন্য NASA JPL থেকে আসল সূর্য আর পৃথিবীর অবস্থান। দিগন্ত আনুমানিক; উচ্চতা \u00d7{k} বাড়িয়ে দেখানো।",
    photoT: "কক্ষপথ থেকে আসল দক্ষিণ মেরু",
    photoD: "এটা NASA-র Lunar Reconnaissance Orbiter-এর তোলা আসল ছবি। মাঝখানে মেরু। কালো জায়গাগুলো গর্তের তলা, যেখানে সূর্য কখনো পৌঁছায় না; উজ্জ্বল কিনারাগুলো বছরের বেশিরভাগ সময় আলো পায়। ঠিক এই পার্থক্য মাথায় রেখেই মিশন পরিকল্পনা করতে হয়।",
    photoPin: "শ্যাকলটন গর্ত (মেরু)",
    photoDark: "সবসময় ছায়ায়",
    photoCredit: "ছবি: NASA/GSFC/Arizona State University, LROC WAC দক্ষিণ মেরু মোজাইক",
  },
  p: {
    kicker: "NASA Space Apps 2026 · CLPS Lunar Mission Browser",
    question: 'চাঁদের দক্ষিণ মেরুতে কোথায় আর কবে নামলে ল্যান্ডার <b>বিদ্যুতের জন্য সূর্যের আলো</b> পাবে আর <em>যোগাযোগের জন্য পৃথিবী দেখতে পাবে</em>?',
    step1: "মেরুর মানচিত্রে একটা সাইট বেছে নাও", step2: "তারিখ বেছে নাও", step3: "রায় পড়ো আর Play চাপো",
    setup: "মিশন সাজাও",
    mapTitle: "দক্ষিণ মেরুর মানচিত্র",
    mapSub: "উপর থেকে মেরুর দিকে তাকিয়ে। প্রতিটা রিং ভরে ওঠে সেই সময়ের ভাগ দিয়ে যখন বিদ্যুৎ আর সিগন্যাল একসাথে থাকে।",
    mapEarth: "পৃথিবীর দিকে", mapSunNow: "এখন সূর্যের দিক",
    dropPin: "পিন বসাও", dropHint: "মানচিত্রে চাপলে সেখানে সাইট যোগ হবে", cancel: "বাতিল",
    offMap: "মানচিত্রের বাইরে",
    pickSite: "ল্যান্ডিং সাইট", pickDates: "তারিখ", startDate: "শুরুর তারিখ", howLong: "কত দিন",
    opt14: "২ সপ্তাহ", opt29: "চাঁদের ১ দিন (২৯.৫ দিন)", opt60: "২ মাস", opt180: "৬ মাস", opt365: "১ বছর",
    dateHint: "চাঁদের এক দিন প্রায় ২৯.৫ পৃথিবী-দিন। মেরুতে বছরের ঋতু অনুযায়ী আলোর পরিমাণও বদলায়।",
    advanced: "উন্নত সেটিংস", missionLen: "মিশন কত দিনের", missionHint: "নামার সেরা সময় বের করতে এটা লাগে।",
    maskLbl: "পৃথিবী অন্তত কত ডিগ্রি উপরে থাকতে হবে", maskHint: "অ্যান্টেনার জন্য অনেক সময় পৃথিবীকে দিগন্তের কয়েক ডিগ্রি উপরে থাকতে হয়। ০ মানে দিগন্তের ঠিক উপরে।",
    horizonLbl: "সাইটের চারপাশের জমির আকার", hSmooth: "মসৃণ চাঁদ (পাহাড় নেই)", hRaised: "পাহাড়ের উপর সাইট (উচ্চতা দাও)", hTerrain: "NASA LOLA-র আসল ভূখণ্ড (ফাইল লোড করো)",
    metres: "মিটার, সমতলের চেয়ে উঁচু", loadCsv: "ভূখণ্ডের ফাইল লোড করো (horizon_mask.py থেকে CSV)",
    csvBad: "ফাইল থেকে দিগন্ত পড়া গেল না। প্রতি লাইনে azimuth_deg,horizon_deg থাকার কথা।",
    csvFar: "লোড হয়েছে, কিন্তু ফাইলটা {lat}, {lon} এর জন্য বানানো, {site} এর জন্য না।",
    addSite: "স্থানাঙ্ক দিয়ে সাইট যোগ করো", latlonHint: "অক্ষাংশ, দ্রাঘিমাংশ ডিগ্রিতে। দক্ষিণ আর পশ্চিম হলে মাইনাস।", addBtn: "সাইট যোগ করো", custom: "আমার সাইট",
    ground: "মাটি আর পাহাড়", sky: "আকাশ",
    skyTitle: "ওখানে দাঁড়ালে যা দেখতে",
    skySub: "তোমার চারপাশে পুরো এক চক্কর, উত্তর থেকে আবার উত্তর পর্যন্ত। ধূসর অংশটা মাটি; এর উপরে যা আছে তা দেখা যায়। হালকা বিন্দুগুলো পুরো সময়ে সূর্য আর পৃথিবীর পথ দেখায়।",
    hSmoothS: "মসৃণ চাঁদ", hRaisedS: "{h} মিটার উঁচু পাহাড়ে", hTerrainS: "আসল ভূখণ্ড",
    play: "চালাও", pause: "থামাও", speed: "গতি", time: "সময়",
    sunUp: "সূর্য উঠে আছে", sunUpN: "সোলার প্যানেল চার্জ হচ্ছে", sunPart: "সূর্য আংশিক ঢাকা", sunPartN: "সূর্যের {p}% দেখা যাচ্ছে", sunDown: "সূর্য ডুবে আছে", sunDownN: "ব্যাটারিতে চলছে",
    earthUp: "পৃথিবী দেখা যাচ্ছে", earthUpN: "বাড়িতে ডেটা পাঠানো যাবে", earthDown: "পৃথিবী আড়ালে", earthDownN: "পৃথিবীর সাথে কোনো সিগন্যাল নেই",
    tlTitle: "পুরো সময় জুড়ে",
    tlSub: "লাইন শূন্যের উপরে মানে সূর্য বা পৃথিবী দেখা যাচ্ছে। নিচের বারগুলো দেখায় কখন বিদ্যুৎ, কখন সিগন্যাল, আর কখন দুটোই আছে। সময় বদলাতে চাপো বা টেনে নাও।",
    yAxis: "দিগন্ত থেকে কত ডিগ্রি উপরে", bPower: "বিদ্যুৎ", bSignal: "সিগন্যাল", bBoth: "দুটোই",
    cmpTitle: "ল্যান্ডিং সাইট তুলনা", cmpSub: "সব সাইটের জন্য একই তারিখ। কোনো সারিতে চাপলে সেটা খুলবে, শিরোনামে চাপলে সাজানো হবে।",
    cSite: "সাইট", cSun: "সূর্যের আলো", cDark: "লম্বা অন্ধকার", cEarth: "পৃথিবী দেখা যায়", cBoth: "দুটোই", cPub: "প্রকাশিত",
    pubHint: '“প্রকাশিত” হলো আসল পাহাড়-পর্বত ধরে করা গবেষণায় পাওয়া দীর্ঘমেয়াদি আলোর হিসাব (<a href="https://en.wikipedia.org/wiki/Peak_of_eternal_light" target="_blank" rel="noopener">সারাংশ</a>)। আমাদের মসৃণ-চাঁদের সংখ্যার সাথে বড় পার্থক্য দেখায় ভূখণ্ড কতটা গুরুত্বপূর্ণ।',
    winTitle: "নামার সেরা সময়",
    winSub: "{site}-এ {n} দিনের মিশনের জন্য। % যত বেশি, বিদ্যুৎ আর সিগন্যাল একসাথে তত বেশি সময় পাওয়া যাবে।",
    winWorst: "দুটো একসাথে না থাকার সবচেয়ে লম্বা সময়: {d}", winSc: "বিদ্যুৎ + সিগন্যাল",
    winNone: "এই তারিখগুলোতে এখানে সূর্য আর পৃথিবী একসাথে থাকে এমন কোনো সময় নেই। লম্বা সময়, অন্য সাইট, বা উন্নত সেটিংসে পৃথিবীর উচ্চতা কমিয়ে দেখো।",
    kSun: "সূর্যের আলো (বিদ্যুৎ)", kSunN: "সময়", kDark: "সবচেয়ে লম্বা অন্ধকার", kDarkN0: "সূর্য ডোবে না", kDarkN: "একটানা",
    kEarth: "পৃথিবী দেখা যায় (সিগন্যাল)", kEarthN: "সময়", kBoth: "বিদ্যুৎ আর সিগন্যাল একসাথে", kBothN: "সময়",
    vGreat: "নামার জন্য ভালো জায়গা", vOk: "সম্ভব, তবে পরিকল্পনা লাগবে", vHard: "টিকে থাকা কঠিন",
    vHeadGreat: "এই তারিখগুলোতে {site} ভালো", vHeadOk: "{site} চলবে, তবে বিরতির জন্য প্রস্তুত থাকতে হবে", vHeadHard: "এই তারিখগুলোতে {site} কঠিন",
    vSunAll: "এই সময়ে এখানে সূর্য একবারও ডোবে না, তাই সোলার প্যানেল সবসময় আলো পায়।",
    vSun: "সূর্য {p}% সময় দেখা যায়। সবচেয়ে লম্বা অন্ধকার সময় {d}।",
    vEarthAll: "পৃথিবী সবসময় দেখা যায়, তাই ল্যান্ডার সবসময় বাড়িতে ডেটা পাঠাতে পারবে।",
    vEarthNone: "এই সময়ে এখানে পৃথিবী একবারও ওঠে না, তাই সরাসরি যোগাযোগ সম্ভব না। রিলে স্যাটেলাইট লাগবে।",
    vEarth: "পৃথিবী {p}% সময় দেখা যায়, অর্থাৎ ততটা সময় ল্যান্ডার যোগাযোগ করতে পারবে। সবচেয়ে লম্বা নীরবতা {d}।",
    vWarn: "সতর্কতা: বেশিরভাগ ছোট ল্যান্ডার কয়েক দিনের বেশি অন্ধকারে টিকতে পারে না। ঠান্ডায় ব্যাটারি শেষ হয়ে যায়।",
    vTerrain: "এখানে পাহাড়হীন মসৃণ চাঁদ ধরা হয়েছে। সাইটভিত্তিক সঠিক উত্তরের জন্য উন্নত সেটিংসে আসল ভূখণ্ড লোড করো।",
    glossTitle: "এখানে ব্যবহৃত শব্দ",
    gloss: [["দিগন্ত (Horizon)", "যেখানে মাটি আর আকাশ মেলে। পাহাড় আর গর্তের কিনারার কারণে কোনো দিকে এটা উঁচু হয়।"],
            ["উচ্চতা কোণ (Elevation)", "সমতল দিগন্ত থেকে কোনো কিছু কত ডিগ্রি উপরে। ০° মানে ঠিক দিগন্তে, ৯০° মানে মাথার উপরে।"],
            ["সরাসরি পৃথিবী-যোগাযোগ", "ল্যান্ডার রেডিওতে পৃথিবীর সাথে কথা বলে। পৃথিবী দিগন্তের উপরে থাকলেই কেবল এটা কাজ করে।"],
            ["চাঁদের দিন", "এক সূর্যোদয় থেকে পরের সূর্যোদয় প্রায় ২৯.৫ পৃথিবী-দিন। মেরু থেকে দূরে এটা মোটামুটি ২ সপ্তাহ আলো আর ২ সপ্তাহ রাত।"],
            ["মেরু কেন আলাদা", "চাঁদের অক্ষ মাত্র ১.৫° হেলানো, তাই মেরুতে সূর্য উপরে না উঠে দিগন্তের চারপাশে ঘোরে।"],
            ["লিব্রেশন (Libration)", "ঘোরার সময় চাঁদ হালকা দোলে, তাই মেরু থেকে পৃথিবী ধীরে ধীরে দিগন্তের উপরে-নিচে ওঠানামা করে।"],
            ["LOLA", "NASA-র Lunar Reconnaissance Orbiter-এর লেজার যন্ত্র, যেটা পুরো চাঁদের উচ্চতার ম্যাপ বানিয়েছে।"],
            ["CLPS", "Commercial Lunar Payload Services: NASA প্রাইভেট কোম্পানিকে টাকা দেয় যাতে তাদের ল্যান্ডারে বিজ্ঞানের যন্ত্র চাঁদে যায়।"]],
    howTitle: "সংখ্যাগুলো কীভাবে হিসাব করা",
    notes: ["<b>সূর্য আর পৃথিবী কোথায়।</b> NASA JPL-এর DE421 ephemeris থেকে, চাঁদের দোলন (librations) সহ, NASA-র LOLA ম্যাপের চাঁদ-ভিত্তিক ফ্রেমে রূপান্তর করা। আলোর যাত্রার সময় আর চাঁদের কেন্দ্র থেকে সাইটের দূরত্বও ধরা হয়েছে। ডেটা ২০২৬–২০৩২, প্রতি ৩ ঘণ্টায়। চাঁদের অবস্থান আলাদা IAU মডেলের সাথে ১৫ আর্কসেকেন্ডের মধ্যে মেলে।",
            "<b>বিদ্যুৎ।</b> সূর্যের চাকতির অন্তত অর্ধেক দিগন্তের উপরে থাকলে গোনা হয়।",
            "<b>সিগন্যাল।</b> পৃথিবীর কেন্দ্র দিগন্ত আর উন্নত সেটিংসের ন্যূনতম উচ্চতার উপরে থাকলে গোনা হয়।",
            "<b>জমির আকার।</b> মসৃণ চাঁদ মানে নিখুঁত গোলক। পাহাড়ের উপর সাইট হলে দিগন্ত একটু নিচে নামে। আসল ভূখণ্ড আসে NASA LOLA উচ্চতার ম্যাপ থেকে, সাথের Python টুল দিয়ে। কেবল আসল ভূখণ্ডই গর্তের কিনারার ছায়া ধরতে পারে।",
            "<b>নামার সেরা সময়।</b> বাছাই করা তারিখে প্রতি ৬ ঘণ্টা পরপর নামার সময় হিসেবে পরীক্ষা করা হয়। স্কোর হলো মিশনের কত অংশে বিদ্যুৎ আর সিগন্যাল একসাথে আছে; সমান হলে যেটায় সবচেয়ে লম্বা বিরতি কম সেটা আগে। নামার মুহূর্তে সূর্য আর পৃথিবী দুটোই থাকতে হবে।",
            "<b>সীমাবদ্ধতা।</b> সাইটের স্থানাঙ্ক প্রকাশিত গবেষণা থেকে, আনুমানিক। রিলে স্যাটেলাইট, গ্রাউন্ড স্টেশনের সময়সূচি, তাপমাত্রা আর ঢালের নিরাপত্তা ধরা হয়নি।"],
    gameCta: "ছায়ার সাথে দৌড় খেলো", gameCtaSub: "একই আকাশের ডেটায় চন্দ্র-রাত পার করে ল্যান্ডার বাঁচিয়ে রাখো।",
  },

  g: {
    tagline: "NASA JPL-এর আসল আকাশের ডেটায় চলা চাঁদে টিকে থাকার গেম",
    intro: "তুমি চাঁদের দক্ষিণ মেরুর কাছে একটা ছোট রোবট ল্যান্ডার চালাচ্ছ। <b>সূর্য ব্যাটারি চার্জ করে, ঠান্ডা ব্যাটারি খরচ করে, আর পৃথিবী দিগন্তের উপরে থাকলেই কেবল ডেটা বাড়িতে পাঠানো যায়।</b> এই গেমের প্রতিটা সূর্যোদয়, সূর্যাস্ত আর পৃথিবী-অস্ত NASA JPL-এর আসল ডেটা থেকে, তুমি যে তারিখে খেলছ সেই তারিখের।",
    scn: {
      vikram: { t: "বিক্রমের রাত", d: "কঠিন", story: "২০২৩ সালে ভারতের বিক্রম ল্যান্ডার ৬৯° দক্ষিণের কাছে নেমে বিজ্ঞানের কাজ করে, কিন্তু প্রথম চন্দ্র-রাতের পর আর জাগেনি। তোমার ল্যান্ডারে টিকে থাকার হিটার আছে। অন্ধকার পার হতে পারবে?", goal: "২ সপ্তাহের রাত পার হয়ে সূর্যোদয়ে জেগে ওঠো।" },
      tipped: { t: "কাত হয়ে পড়া", d: "মাঝারি", story: "২০২৫ সালে একটা ল্যান্ডার কাত হয়ে নেমেছিল, আর সোলার প্যানেল ভুল দিকে মুখ করে ছিল। তোমারটা Malapert পাহাড়ে বাঁকা হয়ে নেমেছে। প্যানেল কেবল এক দিক থেকে সূর্য ধরতে পারে।", goal: "১০ দিনে {g} MB বিজ্ঞানের ডেটা পাঠাও।" },
      peak: { t: "আলোর চূড়া", d: "মুক্ত", story: "তুমিই মিশন প্ল্যানার। দক্ষিণ মেরুর কোনো শৈলশিরায় সাইট আর আগামী এক বছরের যেকোনো তারিখ বেছে নাও, তারপর ১৪ দিনের মিশন চালাও।", goal: "১৪ দিনে যত বেশি সম্ভব ডেটা পাঠাও।" },
    },
    best: "তোমার সেরা: {v}", play: "খেলো",
    howto: [["বিজ্ঞান", "ডেটা সংগ্রহ করে, কিন্তু বিদ্যুৎ খরচ করে।"], ["রেডিও", "ডেটা বাড়িতে পাঠায়, কেবল পৃথিবী উপরে থাকলে।"], ["হাইবারনেট", "অন্ধকারে টিকে থাকতে প্রায় সব বন্ধ করে দেয়।"], ["পূর্বাভাস", "কখন সূর্য আর পৃথিবী উঠবে দেখায়। আগে থেকে পরিকল্পনা করো।"]],
    setupTitle: "কোথায় আর কবে নামবে বেছে নাও", setupSub: "আসল প্ল্যানাররা ঠিক এটাই করে। নিচের পূর্বাভাস তোমার বাছাইয়ের জন্য পরের ১৪ দিনের আলো আর পৃথিবী-যোগাযোগ দেখায়।",
    site: "ল্যান্ডিং সাইট", landDate: "নামার তারিখ (০০:০০ UTC)", back: "পেছনে", launch: "এখানে নামো",
    pvTxt: "পরের ১৪ দিন: সূর্য {s}% সময়, পৃথিবী {e}% সময়, দুটো একসাথে {b}% সময়।",
    abort: "মিশন ছাড়ো", battery: "ব্যাটারি", stored: "পাঠানোর অপেক্ষায়", sent: "পৃথিবীতে পাঠানো", clock: "মিশনের সময়",
    fcTitle: "পূর্বাভাস: পরের ৫ দিন", fcSub: "আসল ephemeris থেকে", now: "এখন", dayN: "+{n}দি",
    sci: "বিজ্ঞানের যন্ত্র", rad: "পৃথিবীতে রেডিও", hib: "হাইবারনেট", on: "চালু", off: "বন্ধ",
    sciS: "+{mb} MB/ঘণ্টা · {w} W খরচ", radS: "{mb} MB/ঘণ্টা · {w} W · পৃথিবী উপরে থাকতে হবে", hibS: "মাত্র {w} W খরচ। বিজ্ঞান আর রেডিও বন্ধ।",
    radWait: "অপেক্ষা: পৃথিবী দিগন্তের নিচে", radIdle: "পাঠানোর মতো কিছু নেই",
    autoPause: "সতর্কবার্তায় থামো", logTitle: "মিশন লগ", pauseLbl: "থামাও", spaceHint: "স্পেস বার চাপলে থামে আর চলে",
    flowIn: "সোলার আসছে", flowOut: "খরচ হচ্ছে", maxMb: "সর্বোচ্চ {n} MB",
    day: "দিন {d}", dayShort: "দিন {d} · {h}:00",
    goal: "লক্ষ্য", goalPeak: "১৪ দিনে যত বেশি সম্ভব পাঠাও",
    exag: "উচ্চতা ×{k} বাড়িয়ে দেখানো", panel: "প্যানেল",
    ev: {
      land: "অবতরণ! সব সিস্টেম চালু।",
      sunsetSoon: "প্রায় {h} ঘণ্টা পর সূর্যাস্ত। ব্যাটারি কি পুরো ভরা?",
      sunset: "সূর্য ডুবে গেছে। হিটার চালু।",
      sunrise: "সূর্যোদয়! প্যানেল আবার চার্জ হচ্ছে।",
      earthsetSoon: "প্রায় {h} ঘণ্টা পর পৃথিবী ডুববে। এখনই ডেটা পাঠাও।",
      earthset: "পৃথিবী ডুবে গেছে। রেডিও যোগাযোগ নেই।",
      earthrise: "পৃথিবী আবার দিগন্তের উপরে।",
      batLow: "ব্যাটারি ২৫% এর নিচে। খরচ কমাও বা হাইবারনেট করো।",
      storeFull: "মেমরি ভরা। নতুন ডেটা হারিয়ে যাচ্ছে।",
      frozen: "ব্যাটারি শেষ। ল্যান্ডার জমে গেছে।",
      done: "মিশন শেষ।", hib: "হাইবারনেট করছে। শুধু টিকে থাকার হিটার চালু।", wake: "জেগে উঠছে। সিস্টেম আবার চালু।",
    },
    win: "মিশন সফল", lose: "ল্যান্ডার হারিয়ে গেছে", done: "মিশন শেষ",
    st: { sent: "পৃথিবীতে পাঠানো", lost: "হারানো ডেটা (মেমরি ভরা)", minBat: "সবচেয়ে কম ব্যাটারি", dark: "অন্ধকারে কাটানো ঘণ্টা", survived: "টিকে ছিল", hours: "{n} ঘণ্টা" },
    replayCap: "মিশন জুড়ে ব্যাটারি (হলুদ = সূর্য উপরে, নীল = পৃথিবী উপরে)।",
    again: "আবার চেষ্টা করো", other: "অন্য মিশন",
    why: {
      title: "কেন এমন হলো?",
      vikramWin: "তুমি <b>{b}%</b> ব্যাটারি নিয়ে রাতে ঢুকে হাইবারনেট করেছ। {w} W খরচে <b>{n} ঘণ্টার</b> অন্ধকার পার হতে টিকে থাকার হিটারের প্রায় <b>{need} Wh</b> লেগেছে।",
      vikramLose: "এই সাইটে রাত ছিল <b>{n} ঘণ্টা</b>। জেগে থাকলে অন্ধকারে ল্যান্ডার {aw} W খরচ করে, তাই পুরো ব্যাটারিও মাত্র প্রায় <b>{last} ঘণ্টা</b> চলে। হাইবারনেট করলেও প্রায় {need} Wh লাগে, তাই রাত শুরুর সময় ব্যাটারি প্রায় ভরা থাকতে হবে।",
      vikramFact: "আসল বিক্রম ল্যান্ডার বানানো হয়েছিল এক চন্দ্র-দিনের জন্য, প্রায় ১৪ পৃথিবী-দিন, আর রাতের পর আর জাগেনি। চন্দ্র-রাতে টিকে থাকা চাঁদের ল্যান্ডারের সবচেয়ে কঠিন সমস্যাগুলোর একটা।",
      tippedTxt: "তোমার প্যানেল {pa}° দিকে মুখ করা ছিল। মেরুর কাছে সূর্য প্রায় ২৯.৫ দিনে পুরো দিগন্ত এক চক্কর ঘোরে, তাই মিশনের একটা অংশে সূর্য প্যানেলের পেছনে ছিল। সূর্য যখন প্যানেলের দিকে ঘুরে এসেছে, তখনই বেশি বিদ্যুৎ পেয়েছ।",
      tippedLose: "প্যানেলে প্রায় কোনো আলো না থাকা অবস্থায় ল্যান্ডার সব চালু রেখেছিল, তাই ব্যাটারি শেষ হয়ে গেছে। প্রথমে হাইবারনেট করো, আর সূর্য প্যানেলের দিকে ঘুরে এলে বিজ্ঞান চালু করো।",
      tippedFact: "ল্যান্ডার কাত হয়ে পড়লে সোলার প্যানেল মাটির দিকে বা ভুল দিকে মুখ করে থাকতে পারে, আর ব্যাটারি চার্জ না হওয়ায় মিশন আগেই শেষ হয়ে যেতে পারে।",
      peakTxt: "{site}-এ তোমার মিশনের {s}% সময় সূর্য আর {e}% সময় পৃথিবী উপরে ছিল, দুটো একসাথে {b}%। গর্তের কিনারা আর শৈলশিরার উঁচু জায়গা বেশি আলো পায়; পৃথিবী-যোগাযোগ নির্ভর করে চাঁদের ধীর দোলনের উপর।",
      peakFact: "একই সাইট অন্য তারিখে চেষ্টা করো, বা প্ল্যানারে সব সাইট একসাথে তুলনা করো।",
      data: "সূর্য আর পৃথিবীর সব অবস্থান তোমার তারিখের জন্য NASA JPL-এর DE421 ephemeris থেকে নেওয়া। চাঁদকে মসৃণ ধরা হয়েছে (পাহাড় নেই), তাই আসল কিনারার সাইট আরও ভালো করতে পারে।",
      open: "এই সাইট প্ল্যানারে খোলো",
    },
  },
};

export type Lang = "en" | "bn";
export const DICT: Record<Lang, Dict> = { en, bn };
