/* Spanish. Any key left out here falls back to English. */
import type { Dict } from "./dict";

type DeepPartial<T> = T extends unknown[] ? T : T extends object ? { [K in keyof T]?: DeepPartial<T[K]> } : T;

export const es: DeepPartial<Dict> = {
  brand: "Ventana del Polo Sur",
  nav: { home: "Resumen", planner: "Planificador", game: "Corre contra la sombra", missions: "Misiones" },
  theme: { toLight: "Cambiar a tema claro", toDark: "Cambiar a tema oscuro" },
  loading: "Cargando las efemérides de JPL…",
  loadFail: "No se pudieron cargar los datos del cielo. Recarga la página para intentarlo de nuevo.",
  footer: "Posiciones del Sol y la Tierra: efemérides DE421 de NASA JPL con libraciones lunares · marco ME de la Luna · todas las horas en UTC · Hecho para NASA Space Apps 2026, CLPS Lunar Mission Browser",
  compass: ["N", "NE", "E", "SE", "S", "SO", "O", "NO", "N"],
  utc: "UTC",
  sun: "Sol", earth: "Tierra",
  days: "{n} días", day1: "1 día", hours: "{n} horas", hour1: "1 hora", zero: "ninguna",

  l: {
    kicker: "En vivo · efemérides DE421 de NASA JPL",
    title: "Persigue la <em>luz</em> en el fondo de la Luna.",
    ctaPlanner: "Abrir el Planificador", ctaGame: "Jugar a Corre contra la sombra",
    sunAtPole: "Sol sobre el polo", sitesLit: "Sitios con sol", speed: "{n} d/s",
    terrainNote: "El relieve es ilustrativo. Las direcciones del Sol y la Tierra son reales para la hora mostrada. Arrastra para moverte en el tiempo.",
    sunUp: "Sol arriba", sunDown: "Sol abajo", earthUp: "Tierra a la vista", earthDown: "Tierra oculta",
  },
  s: {
    back: "Resumen", open: "Abrir en el Planificador",
    now: "Ahora mismo", monthKicker: "Próximos 30 días",
    eventsTitle: "Lo que viene", noEvents: "No hay amaneceres, atardeceres ni salidas o puestas de la Tierra en los próximos 30 días.",
    others: "Otros sitios",
    ev: { sunrise: "Amanecer", sunset: "Atardecer", earthrise: "Sale la Tierra", earthset: "Se pone la Tierra" },
  },
  p2: {
    title: "Planifica un alunizaje",
    intro: "Elige un sitio y unas fechas. Mira cuándo un módulo recibe luz solar para tener energía y puede ver la Tierra para enviar datos a casa.",
    s1: "Elige un sitio de alunizaje", s1h: "Haz clic en un punto del mapa o en un nombre de la lista.",
    listHead: "Energía + señal",
    s2: "Elige las fechas", s2h: "¿Cuándo estaría allí el módulo?",
    s3: "Resultado",
    vGreat: "Bueno para alunizar", vOk: "Posible con planificación", vHard: "Arriesgado",
    bodyGreat: "Mucha luz solar y contacto regular con la Tierra.",
    bodyOk: "Habrá cortes de energía o de contacto por radio.",
    bodyHard: "Largos periodos de oscuridad o poco contacto con la Tierra.",
    warn: "Aquí las noches duran más de 4 días. La mayoría de los módulos pequeños se congelan.",
    cSun: "Luz solar", cDark: "Noche más larga", cEarth: "Tierra a la vista", cBoth: "Energía + señal",
    skyT: "Mira alrededor del sitio", skyH: "Pulsa Reproducir para ver al Sol y la Tierra moverse por el cielo. Lo gris es el suelo.",
    tlT: "Todo el periodo de un vistazo", tlH: "Por encima de 0° significa visible. Las barras muestran energía, señal o ambas. Arrastra para moverte en el tiempo.",
    cmpT: "Compara todos los sitios", cmpH: "Las mismas fechas para cada sitio. Haz clic en una fila para cambiar.",
    winT: "Mejores momentos para alunizar", winH: "Mejores horas de inicio para una misión de {n} días.",
    winGap: "corte más largo: {d}",
    more: "Saber más: términos y métodos",
    smoothChip: "lisa", smoothTip: "No hay datos de terreno para este sitio: se calcula sobre una Luna lisa",
    terrainOn: "Incluye montañas reales: horizonte calculado con datos de elevación LOLA de la NASA.",
    terrainOff: "Luna lisa: aquí no hay datos de terreno, así que no se incluyen las montañas.",
    terrainRaised: "Modelo simple de colina ({h} m sobre las llanuras), no es terreno real.",
    pubTip: "Luz solar a largo plazo según estudios que incluyen montañas reales",
  },
  p3: {
    share: "Copiar enlace a este plan", copied: "Enlace copiado", print: "Imprimir o guardar como PDF",
    briefT: "Informe de alunizaje", briefMission: "misión de {n} días",
  },
  l2: {
    lede: "El Sol apenas se asoma en el polo sur de la Luna. Descubre dónde y cuándo un módulo recibe luz solar y puede ver la Tierra.",
    liveT: "Ahora mismo en la Luna",
    ready: "Listo", noPower: "Sin energía", noSignal: "Sin señal", offline: "A oscuras y en silencio",
    howT: "Cómo planificar un alunizaje", howH: "Tres pasos en el Planificador.",
    h1: "Elige un sitio", h1d: "Haz clic en un punto del mapa polar.",
    h2: "Elige las fechas", h2d: "Decide cuándo llega el módulo.",
    h3: "Lee el resultado", h3d: "Mira la energía, la señal y los mejores momentos para alunizar.",
    gameT: "Aprende jugando", gameD: "Mantén vivo un módulo durante la noche lunar, con los mismos datos reales del cielo.",
    api: "Desarrolladores: API JSON",
  },
  l3: {
    help: "Elige un sitio para ver su cielo. Desliza la barra para mirar hasta 30 días adelante.",
    count: "de {m} sitios pueden hacer funcionar un módulo", now: "ahora mismo", at: "dentro de {d}",
    pick: "Sitios de alunizaje",
    skyAlt: "El cielo desde {site}: dónde están el Sol y la Tierra, sobre o bajo el horizonte.",
    below: "bajo el horizonte", hill: "oculto por el terreno",
    sunOn: "Hay sol. Los paneles solares se están cargando.", sunOff: "No hay sol. Funciona con la batería.", sunBlocked: "El Sol está arriba, pero las colinas o la pared de un cráter lo tapan.",
    sunEnds: "El sol se va en unos {d}", sunBack: "El sol vuelve en unos {d}",
    earthOn: "La Tierra está a la vista. La radio funciona.", earthOff: "La Tierra está oculta. No hay contacto con casa.",
    earthEnds: "La Tierra se pone en unos {d}", earthBack: "La Tierra sale en unos {d}",
    noChange: "Sigue así el resto de los 30 días",
    share: "Energía y señal a la vez, durante estos 30 días",
    details: "Todos los detalles", plan: "Planificar un alunizaje aquí",
    play: "Reproducir 30 días", pause: "Pausa", reset: "Volver a ahora", slider: "Tiempo, desde ahora hasta 30 días adelante",
    legSun: "Luz solar", legEarth: "Tierra a la vista", end: "dentro de {d}",
  },
  s2: {
    monthH: "Por encima de 0° significa visible desde el sitio.",
    movedNote: "Terreno real de NASA LOLA. Colocado en el pico de luz según LOLA, a {m} m del punto publicado (cada mapa sitúa el pico en un lugar un poco distinto).",
    yearT: "Próximos 12 meses", yearH: "Parte del año con luz solar, con la Tierra a la vista y con ambas.",
    eventsH: "Próximos amaneceres, atardeceres y puestas de la Tierra (UTC).",
  },
  g2: {
    intro: "Mantén vivo un pequeño módulo cerca del polo sur de la Luna. El Sol lo carga, el frío lo descarga y solo puede enviar datos mientras la Tierra está arriba.",
    go: "Continuar",
    tip: {
      ok: "¡Todo bien! Mira el pronóstico para saber cuándo se pone el Sol.",
      send: "¡La ciencia va volando hacia la Tierra!",
      sci: "La batería está bien. ¡Enciende los instrumentos!",
      radio: "¡La Tierra está arriba! Enciende la radio para enviar tu ciencia a casa.",
      full: "La memoria está llena. Apaga la ciencia hasta que vuelva la Tierra.",
      dark: "Está oscuro y hace frío. ¡Hiberna para ahorrar batería!",
      low: "¡Queda poca batería! Apaga cosas o hiberna.",
      sleep: "Shh… ahorrando energía hasta que vuelva el Sol.",
      wake: "¡Mucho sol! Despierta y haz algo de ciencia.",
      frozen: "Brrr… se acabó la batería.",
    },
    bandHi: "Conoce a tu módulo",
    aiNote: "Las imágenes de las misiones, la escena de arriba y la imagen de carga son ilustraciones generadas con IA, no fotos reales. Todo lo que calcula el juego viene de datos reales de NASA JPL.",
    sndOn: "Sonido activado", sndOff: "Sonido desactivado",
    share: "Compartir mi puntuación", copied: "Copiado",
    shareText: "Corre contra la sombra, reto diario {day}: {mb} MB enviados a casa {stars}",
    x: {
      title: "¿Por qué es difícil el polo sur?", sub: "Toca los puntos numerados para descubrirlo.",
      alt: "Ilustración del polo sur de la Luna: el Sol en el horizonte, la Tierra baja en un cielo negro, una cresta brillante y un cráter profundo y oscuro.",
      sun: { t: "El Sol se queda bajo", d: "En el polo el Sol nunca sube mucho. Se desliza por el horizonte, así que hasta una colina pequeña puede taparlo durante días." },
      earth: { t: "La Tierra es la única línea de teléfono", d: "Un módulo habla con casa por radio. Cuando la Tierra baja del horizonte, los mensajes se detienen hasta que vuelve." },
      ridge: { t: "El terreno alto recibe más luz", d: "Las crestas y los bordes de los cráteres se asoman al sol. Algunos están iluminados casi todo el año, perfecto para paneles solares." },
      shadow: { t: "Sombras muy largas", d: "Con el Sol tan bajo, hasta una roca pequeña da una sombra mucho más larga que ella. Un módulo atrapado en una no puede cargar su batería." },
      crater: { t: "Cráteres que nunca ven el Sol", d: "El fondo de algunos cráteres lleva miles de millones de años a oscuras. Están entre los lugares más fríos que conocemos y pueden esconder agua helada." },
    },
  },
  w: {
    title: "Por qué es difícil",
    help: "El mismo Sol, la misma Tierra. Solo cambia dónde está el módulo. Cambia de lugar y mira un día lunar.",
    canvasLabel: "Un módulo en el polo sur lunar con el Sol y la Tierra moviéndose por el horizonte",
    where: "Dónde está el módulo", ridge: "En una cresta", crater: "En un cráter",
    pOn: "Con energía", pOff: "Sin energía", rOn: "Con radio", rOff: "Sin radio",
    msgBoth: "Sol y Tierra a la vista: el módulo puede trabajar.",
    msgNoSun: "El Sol está detrás del horizonte: sin energía, el módulo se congela.",
    msgNoEarth: "La Tierra ha bajado del horizonte: no hay contacto por radio.",
    msgNone: "Sin Sol y sin Tierra: el módulo debe dormir y esperar.",
    day: "Día lunar · día {d} de 30",
    tally: "Durante este día lunar",
    tPower: "energía", tRadio: "radio",
    note: "Posiciones reales del Sol y la Tierra según NASA JPL para el próximo día lunar. Los horizontes son ilustrativos; las alturas están exageradas ×{k}.",
    photoT: "El polo sur real, desde la órbita",
    photoD: "Este es un mosaico de fotos reales del Lunar Reconnaissance Orbiter de la NASA. El polo está en el centro. Las manchas negras son fondos de cráteres a los que el Sol nunca llega; los bordes brillantes reciben luz la mayor parte del año. Ese contraste es justo lo que una misión tiene que planificar.",
    photoPin: "Cráter Shackleton (el polo)",
    photoDark: "Siempre en sombra",
    photoCredit: "Imagen: NASA/GSFC/Arizona State University, mosaico LROC WAC del polo sur",
  },
  p: {
    setup: "Configuración de la misión",
    mapTitle: "Mapa polar sur",
    mapEarth: "hacia la Tierra", mapSunNow: "Dirección del Sol ahora",
    dropPin: "Poner un marcador", dropHint: "Haz clic en el mapa para añadir un sitio ahí", cancel: "Cancelar",
    startDate: "Fecha de inicio", howLong: "Duración",
    opt14: "2 semanas", opt29: "1 día lunar (29,5 días)", opt60: "2 meses", opt180: "6 meses", opt365: "1 año",
    advanced: "Ajustes avanzados", missionLen: "Duración de la misión (días)", missionHint: "Se usa para ordenar los mejores días para alunizar.",
    maskLbl: "La Tierra debe estar al menos a esta altura (°)", maskHint: "Las antenas suelen necesitar la Tierra unos grados sobre el horizonte. 0 significa justo por encima.",
    horizonLbl: "Forma del suelo alrededor del sitio", hSmooth: "Luna lisa (sin montañas)", hRaised: "Sitio en una colina (indica la altura)", hTerrain: "Terreno real de NASA LOLA (cargar archivo)",
    metres: "metros sobre las llanuras", loadCsv: "Cargar un archivo de terreno (CSV de horizon_mask.py)",
    csvBad: "No se pudo leer un horizonte en ese archivo. Se esperaban líneas con azimuth_deg,horizon_deg.",
    csvFar: "Cargado, pero este archivo se hizo para {lat}, {lon}, no para {site}.",
    addSite: "Añadir un sitio por coordenadas", latlonHint: "Latitud y longitud en grados. El sur es negativo, el oeste es negativo.", addBtn: "Añadir sitio", custom: "Mi sitio",
    ground: "Suelo y montañas", sky: "cielo",
    play: "Reproducir", pause: "Pausa", speed: "Velocidad", time: "Tiempo",
    sunUp: "El Sol está arriba", sunUpN: "los paneles solares se están cargando", sunPart: "El Sol está medio oculto", sunPartN: "se ve el {p}% del Sol", sunDown: "El Sol está abajo", sunDownN: "funcionando con baterías",
    earthUp: "La Tierra es visible", earthUpN: "puede enviar datos a casa", earthDown: "La Tierra está oculta", earthDownN: "sin señal con la Tierra",
    yAxis: "grados sobre el horizonte", bPower: "Energía", bSignal: "Señal", bBoth: "Ambas",
    cSite: "Sitio", cBoth: "Ambas", cPub: "Publicado",
    winSc: "energía + señal",
    winNone: "Ninguna hora de alunizaje en estas fechas tiene el Sol y la Tierra arriba a la vez aquí. Prueba fechas más largas, otro sitio, o baja la altura de la Tierra en Ajustes avanzados.",
    gloss: [["Horizonte", "La línea donde el suelo se junta con el cielo. Las montañas y los bordes de cráteres lo hacen más alto en algunas direcciones."],
            ["Elevación", "A qué altura está algo sobre el horizonte plano, en grados. 0° es justo en el horizonte, 90° es recto hacia arriba."],
            ["Enlace directo con la Tierra", "El módulo hablando con la Tierra por radio. Solo funciona cuando la Tierra está sobre el horizonte."],
            ["Día lunar", "Unos 29,5 días terrestres de un amanecer al siguiente. Lejos de los polos, son unas 2 semanas de luz y 2 semanas de noche."],
            ["Por qué el polo es especial", "El eje de la Luna está inclinado solo 1,5°, así que en el polo el Sol da vueltas por el horizonte en lugar de subir alto."],
            ["Libración", "La Luna se bambolea un poco al orbitar, así que desde el polo la Tierra sube y baja lentamente del horizonte."],
            ["LOLA", "Un láser del Lunar Reconnaissance Orbiter de la NASA que midió la altura de toda la Luna."],
            ["CLPS", "Commercial Lunar Payload Services: la NASA paga a empresas para llevar ciencia a la Luna en sus módulos."]],
    notes: ["<b>Dónde están el Sol y la Tierra.</b> De las efemérides DE421 de NASA JPL, incluido el bamboleo de la Luna (libraciones), convertidas al marco fijo a la Luna que usan los mapas LOLA de la NASA. Se incluyen el tiempo de viaje de la luz y la distancia del sitio al centro de la Luna. Los datos cubren 2024–2032 en pasos de 3 horas. La orientación de la Luna coincide con el modelo independiente de la IAU con menos de 15 segundos de arco de diferencia.",
            "<b>Energía.</b> Se cuenta cuando al menos la mitad del disco del Sol está sobre el horizonte en la dirección del Sol.",
            "<b>Señal.</b> Se cuenta cuando el centro de la Tierra está sobre el horizonte más la altura mínima indicada en Ajustes avanzados.",
            "<b>Forma del suelo.</b> Luna lisa usa una esfera perfecta. Sitio en una colina baja el horizonte como ocurriría en un pico sobre llanuras. Terreno real usa un horizonte calculado con los mapas de elevación LOLA de la NASA y la herramienta de Python incluida. Solo el terreno real capta las sombras de los bordes de los cráteres.",
            "<b>Mejores momentos para alunizar.</b> Se prueba cada 6 horas de las fechas elegidas como hora de alunizaje. La puntuación es la parte de la misión con energía y señal a la vez; en caso de empate gana el corte más corto. Para alunizar, el Sol y la Tierra deben estar arriba.",
            "<b>Límites.</b> Las coordenadas de los sitios vienen de estudios publicados y son aproximadas. No se incluyen satélites de enlace, horarios de estaciones terrestres, temperatura ni seguridad por pendientes."],
  },
  m: {
    title: "Alunizajes reales, repetidos",
    intro: "Hasta ahora tres módulos CLPS han llegado a la Luna. Este es el cielo que vio cada uno, calculado con el mismo motor que el Planificador, junto a lo que pasó de verdad.",
    pick: "Misiones",
    landed: "Alunizó", lastContact: "Último contacto", toLanding: "Volver al alunizaje", slider: "Tiempo a lo largo de la misión",
    skyAlt: "El cielo desde el sitio de alunizaje de {name}",
    stBefore: "Aún no ha alunizado", stOver: "Misión terminada",
    checkT: "Lo que calcula el modelo", checkH: "A partir de la tabla de JPL, para el lugar y la hora reales del alunizaje. Las notas verdes lo comparan con lo que informó la misión.",
    fSun: "Sol al tocar suelo", fEarth: "Tierra al tocar suelo", fSunrise: "Amanecer antes del alunizaje", fSunset: "Atardecer después del alunizaje", fEclipse: "Sol totalmente detrás de la Tierra",
    above: "{x}° sobre el horizonte",
    afterSunrise: "Tocó suelo {d} después del amanecer",
    endAfter: "El último contacto llegó {d} después de este atardecer", endBefore: "La misión terminó {d} antes de este atardecer",
    eclipseNote: "Blue Ghost fotografió este eclipse desde la superficie",
    showsT: "Lo que muestra la repetición",
    smooth: "Estos tres sitios se calculan sobre una Luna lisa: sus colinas y cráteres locales no están en el modelo.",
    src: "Las horas, los lugares y los resultados de los alunizajes vienen de los informes públicos de la NASA y de los equipos de las misiones.",
    open: "Abrir este lugar en el Planificador",
    im1: {
      tag: "Alunizó inclinado",
      what: "Odysseus logró el primer alunizaje suave de Estados Unidos desde el Apolo 17 en 1972, y el primero de una empresa privada. Se le rompió una pata al tocar suelo y quedó inclinado unos 30°. Funcionó durante cerca de una semana.",
      shows: "Al tocar suelo el Sol estaba a {sun}° y la Tierra a {earth}°, así que este lugar tenía energía y enlace de radio. El modelo sitúa el atardecer varios días después del final de la misión: inclinado, Odysseus dejó de recibir luz en sus paneles antes de que el Sol se pusiera de verdad.",
    },
    bg1: {
      tag: "Éxito total",
      what: "Blue Ghost logró el primer alunizaje comercial totalmente exitoso. Trabajó durante un día lunar entero, unos 14 días terrestres, y unas horas más ya de noche.",
      shows: "Según el modelo, el Sol salió en el sitio unas horas antes del alunizaje y se puso la tarde del 16 de marzo de 2025, la misma tarde en que Blue Ghost envió sus últimos datos. También muestra al Sol pasando por completo detrás de la Tierra el 14 de marzo: el eclipse que Blue Ghost fotografió.",
    },
    im2: {
      tag: "Alunizó de lado",
      what: "Athena alunizó más cerca del polo sur que ningún módulo anterior, a unos 250 m de su objetivo en Mons Mouton. Quedó de lado dentro de un cráter pequeño, no pudo recargarse y la misión terminó al día siguiente.",
      shows: "Al tocar suelo el Sol estaba solo a {sun}° sobre el horizonte. Tan bajo, la pared de un cráter basta para dejar un módulo en sombra, y de lado dentro de un cráter Athena no tenía forma de recargarse. Por eso el Planificador cuenta cada grado del horizonte.",
    },
  },
  g: {
    tagline: "Un juego de supervivencia lunar con datos reales del cielo de NASA JPL",
    scn: {
      vikram: { t: "La noche de Vikram", d: "Difícil", story: "En 2023, el módulo indio Vikram alunizó cerca de los 69°S, hizo su ciencia y no volvió a despertar tras su primera noche lunar. Tu módulo tiene calefactores de supervivencia. ¿Podrá sobrevivir a la oscuridad?", goal: "Sobrevive a la noche de 2 semanas y despierta al amanecer." },
      tipped: { t: "Volcado", d: "Medio", story: "En 2025, un módulo alunizó de lado y sus paneles solares apuntaban al lugar equivocado. El tuyo ha caído torcido en la montaña Malapert. El panel solo recibe el Sol desde una dirección.", goal: "Envía {g} MB de ciencia a casa en 10 días." },
      peak: { t: "Pico de luz", d: "Libre", story: "Sé quien planifica la misión. Elige un sitio en las crestas del polo sur y una fecha de alunizaje en el próximo año, y luego vuela una misión de 14 días.", goal: "Envía a casa toda la ciencia que puedas en 14 días." },
      daily: { t: "Reto de hoy", d: "Diario", story: "Una misión nueva cada día, la misma para todos: diez días, un sitio y una fecha elegidos por el calendario. Supera la puntuación de tus amigos.", goal: "Envía a casa toda la ciencia que puedas en 10 días." },
    },
    best: "Tu mejor marca: {v}", play: "Jugar",
    howto: [["Ciencia", "Recoge datos pero gasta energía."], ["Radio", "Envía datos a casa, solo mientras la Tierra está arriba."], ["Hibernar", "Apaga casi todo para sobrevivir a la oscuridad."], ["Pronóstico", "Muestra cuándo estarán arriba el Sol y la Tierra. Planifica con tiempo."]],
    setupTitle: "Elige dónde y cuándo alunizar", setupSub: "Quienes planifican misiones hacen justo esto. El pronóstico de abajo muestra los próximos 14 días de luz solar y contacto con la Tierra para tu elección.",
    site: "Sitio de alunizaje", landDate: "Fecha de alunizaje (00:00 UTC)", back: "Atrás", launch: "Alunizar aquí",
    pvTxt: "Próximos 14 días: Sol arriba el {s}% del tiempo, Tierra arriba el {e}%, ambos a la vez el {b}%.",
    abort: "Abandonar misión", battery: "Batería", stored: "Ciencia en espera", sent: "Enviado a la Tierra", clock: "Tiempo de misión",
    fcTitle: "Pronóstico: próximos 5 días", fcSub: "de las efemérides reales", now: "ahora", dayN: "+{n}d",
    sci: "Instrumentos científicos", rad: "Radio a la Tierra", hib: "Hibernar", on: "SÍ", off: "NO",
    sciS: "+{mb} MB/h · gasta {w} W", radS: "{mb} MB/h · {w} W · necesita la Tierra arriba", hibS: "Gasta solo {w} W. La ciencia y la radio se detienen.",
    radWait: "Esperando: la Tierra está bajo el horizonte", radIdle: "Aún no hay nada que enviar",
    autoPause: "Pausar en los avisos", logTitle: "Registro de la misión", pauseLbl: "Pausa", spaceHint: "La barra espaciadora pausa y reanuda",
    flowIn: "Entrada solar", flowOut: "Consumo", maxMb: "máx. {n} MB",
    day: "Día {d}", dayShort: "Día {d} · {h}:00",
    goal: "Objetivo", goalPeak: "envía todo lo que puedas en 14 días",
    exag: "alturas exageradas ×{k}", panel: "panel",
    ev: {
      land: "¡Contacto! Los sistemas están en línea.",
      sunsetSoon: "El Sol se pone en unas {h} horas. ¿Tienes la batería llena?",
      sunset: "El Sol se ha puesto. Los calefactores están encendidos.",
      sunrise: "¡Amanece! Los paneles vuelven a cargar.",
      earthsetSoon: "La Tierra se pone en unas {h} horas. Envía tus datos ya.",
      earthset: "La Tierra se ha puesto. Sin contacto por radio.",
      earthrise: "La Tierra vuelve a estar sobre el horizonte.",
      batLow: "Batería por debajo del 25%. Reduce el consumo o hiberna.",
      storeFull: "Memoria llena. Se está perdiendo ciencia nueva.",
      frozen: "Batería vacía. El módulo se ha congelado.",
      done: "Misión completada.", hib: "Hibernando. Solo funcionan los calefactores de supervivencia.", wake: "Despertando. Sistemas en línea de nuevo.",
    },
    win: "Misión cumplida", lose: "Módulo perdido", done: "Misión completada",
    st: { sent: "Enviado a la Tierra", lost: "Ciencia perdida (memoria llena)", minBat: "Batería más baja", dark: "Horas a oscuras", survived: "Sobrevivió", hours: "{n} h" },
    replayCap: "Batería durante la misión (ámbar = Sol arriba, azul = Tierra arriba).",
    again: "Intentar de nuevo", other: "Otras misiones",
    why: {
      title: "¿Por qué pasó eso?",
      vikramWin: "Entraste en la noche con <b>{b}%</b> de batería e hibernaste. A {w} W, los calefactores de supervivencia necesitaron unos <b>{need} Wh</b> para pasar <b>{n} horas</b> de oscuridad.",
      vikramLose: "La noche en este sitio duró <b>{n} horas</b>. Despierto, el módulo gasta {aw} W a oscuras, así que una batería llena dura solo unas <b>{last} horas</b>. Incluso hibernando necesita unos {need} Wh, así que debe empezar la noche casi lleno.",
      vikramFact: "El módulo Vikram real se diseñó para un día lunar, unos 14 días terrestres, y no despertó tras la noche. Sobrevivir a la noche lunar es uno de los problemas más difíciles para los módulos lunares.",
      tippedTxt: "Tu panel miraba hacia {pa}°. Cerca del polo el Sol da una vuelta completa al horizonte cada 29,5 días, así que pasó parte de la misión detrás de tu panel. La energía llegó sobre todo cuando el Sol giró hacia él.",
      tippedLose: "Tu módulo lo tuvo todo encendido mientras el panel recibía poca o ninguna luz, y la batería se vació. Hiberna al principio y enciende la ciencia cuando el Sol gire hacia el panel.",
      tippedFact: "Cuando un módulo vuelca, los paneles solares pueden quedar mirando al suelo o en la dirección equivocada, y la misión puede acabar antes porque las baterías no se recargan.",
      peakTxt: "En {site}, el Sol estuvo arriba el {s}% y la Tierra el {e}% de tu misión, ambos a la vez el {b}%. Los sitios altos en bordes de cráteres y crestas reciben más luz; el contacto con la Tierra depende del lento bamboleo de la Luna.",
      peakFact: "Prueba el mismo sitio en otra fecha, o compara todos los sitios a la vez en el Planificador.",
      data: "Todas las posiciones del Sol y la Tierra vienen de las efemérides DE421 de NASA JPL para tus fechas exactas. La Luna se trata como lisa (sin montañas), así que los sitios reales en los bordes pueden ir aún mejor.",
      open: "Abrir este sitio en el Planificador",
    },
  },
};
