/* All UI words, English and Bengali (Spanish is in dict-es.ts). Strings may contain {placeholders}; some contain trusted inline HTML. */

import { es } from "./dict-es";

const en = {
  brand: "Hyphen", tagline: "Mission Moonlight",
  nav: { home: "Overview", planner: "Planner", game: "Race the Shadow", missions: "Missions", ask: "Ask Hyphen AI", adv: "Adventure Moon" },
  theme: { toLight: "Switch to light theme", toDark: "Switch to dark theme" },
  loading: "Loading the JPL ephemeris…",
  loadFail: "Couldn't load the sky data. Reload the page to try again.",
  footer: "Sun and Earth positions: NASA JPL DE421 ephemeris with lunar librations · Moon ME frame · all times UTC · Built for NASA Space Apps 2026, CLPS Lunar Mission Browser",
  compass: ["N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"],
  utc: "UTC",
  sun: "Sun", earth: "Earth",
  days: "{n} days", day1: "1 day", hours: "{n} hours", hour1: "1 hour", zero: "none",

  l: {
    kicker: "Live · NASA JPL DE421 ephemeris",
    title: "Chase the <em>light</em> at the bottom of the Moon.",
    lede: "At the lunar south pole the Sun never climbs more than a degree or two. It circles the horizon and drags shadows tens of kilometres long across the crater rims. Pick where and when to land, and see exactly when a lander has power and a line home.",
    ctaPlanner: "Open the Planner", ctaGame: "Play Race the Shadow",
    f1: "tilt of the Moon\u2019s axis", f2: "one sunrise to the next", f3: "Earth\u2019s wobble in the sky",
    sunAtPole: "Sun above the pole", sitesLit: "Sites in sunlight", speed: "{n} d/s",
    terrainNote: "Relief is illustrative. Sun and Earth directions are real for the time shown. Drag to scrub.",
    liveKicker: "Right now on the Moon", liveTitle: "{n} of {total} sites have power and a line to Earth",
    sunUp: "Sun up", sunDown: "Sun down", earthUp: "Earth in view", earthDown: "Earth hidden", details: "Details",
    needKicker: "The problem", needTitle: "A south-pole lander needs two things at once",
    powerTag: "Power", powerTitle: "Sunlight on the panels",
    powerText: "The Sun skims the horizon, so a hill a few kilometres away can hide it for days. Nights on crater floors last weeks; high rims can stay lit for most of a year.",
    linkTag: "Link", linkTitle: "Earth above the horizon",
    linkText: "Earth hangs low in the sky from the pole and slowly bobs up and down as the Moon wobbles. When it dips below the skyline, the lander can\u2019t call home without a relay.",
    toolKicker: "The Planner", toolTitle: "Everything a mission planner needs, in one screen",
    next30: "Next 30 days · {site}",
    tools: {
      compare: { t: "Compare sites side by side", d: "Sunlight, longest night, Earth visibility and time with both, for every candidate on the same dates." },
      scrub: { t: "Stand on the site and press Play", d: "A 360° skyline with the Sun and Earth moving across it, hour by hour." },
      windows: { t: "Find the best time to land", d: "Every 6 hours is tested as a touchdown; the top windows are ranked by power and signal together." },
      terrain: { t: "Bring real LOLA terrain", d: "Load a horizon mask made from NASA elevation maps and every number updates to the true skyline." },
    },
    gameKicker: "For classrooms and the curious", gameTitle: "Race the Shadow",
    gameText: "Keep a small lander alive through the lunar night. Every sunrise and Earth-set in the game comes from the same real ephemeris.",
    apiKicker: "For developers", apiTitle: "The same numbers, as JSON",
    apiText: "Every page here is computed on the server from the DE421 table. Query any site, or any latitude and longitude.",
  },
  s: {
    back: "Overview", kicker: "Landing site", open: "Open in the Planner", pub: "{p}% lit long-term in terrain studies",
    now: "Right now", monthKicker: "Next 30 days", monthTitle: "Sun and Earth above the horizon",
    eventsTitle: "Coming up", noEvents: "No sunrises, sunsets, Earth-rises or Earth-sets in the next 30 days.",
    yearTitle: "The next 12 months", others: "Other sites",
    ev: { sunrise: "Sunrise", sunset: "Sunset", earthrise: "Earth rises", earthset: "Earth sets" },
  },
  p2: {
    title: "Plan a landing",
    intro: "Pick a site and dates. See when a lander gets sunlight for power and can see Earth to send data home.",
    s1: "Pick a landing site", s1h: "Click a dot on the map or a name in the list.",
    listHead: "Power + signal",
    s2: "Pick the dates", s2h: "When would the lander be there?",
    s3: "Result",
    vGreat: "Good for landing", vOk: "Workable with planning", vHard: "Risky",
    bodyGreat: "Plenty of sunlight and regular contact with Earth.",
    bodyOk: "Expect breaks in power or radio contact.",
    bodyHard: "Long dark periods or little contact with Earth.",
    warn: "Nights last more than 4 days here. Most small landers freeze.",
    cSun: "Sunlight", cDark: "Longest night", cEarth: "Earth in view", cBoth: "Power + signal",
    skyT: "Look around the site", skyH: "Press Play to watch the Sun and Earth move across the sky. Grey is the ground.",
    tlT: "The whole period at a glance", tlH: "Above 0° means visible. The bars show power, signal, or both. Drag to move in time.",
    cmpT: "Compare all sites", cmpH: "Same dates for every site. Click a row to switch.",
    winT: "Best times to land", winH: "Top start times for a {n}-day mission.",
    winGap: "longest break: {d}",
    more: "Learn more: words and methods",
    smoothChip: "smooth", smoothTip: "No terrain data for this site: computed on a smooth Moon",
    terrainOn: "Includes real mountains: skyline from NASA LOLA elevation data.",
    terrainOff: "Smooth Moon: no terrain data here, so mountains are not included.",
    terrainRaised: "Simple hill model ({h} m above the plains), not real terrain.",
    pubTip: "Long-term sunlight from studies that include real mountains",
  },
  l2: {
    lede: "The Sun barely rises at the Moon\u2019s south pole. Find where and when a lander gets sunlight and can see Earth.",
    liveT: "Right now on the Moon", liveH: "Live from NASA JPL data. A site is ready when it has sunlight and a view of Earth.",
    colSite: "Site", colSun: "Sunlight", colEarth: "Earth", colStatus: "Status",
    ready: "Ready", noPower: "No power", noSignal: "No signal", offline: "Dark and silent",
    up: "Up", down: "Down", visible: "Visible", hidden: "Hidden",
    whyT: "Why it\u2019s hard", whyH: "A lander needs both of these at the same time.",
    powerT: "Sunlight for power", powerD: "The Sun skims the horizon, so a nearby hill can hide it for days.",
    linkT: "Earth in view for radio", linkD: "Earth sits low in the sky and slowly bobs below the horizon.",
    howT: "How to plan a landing", howH: "Three steps in the Planner.",
    h1: "Pick a site", h1d: "Click a spot on the polar map.",
    h2: "Pick dates", h2d: "Choose when the lander arrives.",
    h3: "Read the result", h3d: "See power, signal and the best landing times.",
    gameT: "Learn by playing", gameD: "Keep a lander alive through the lunar night, on the same real sky data.",
    api: "Developers: JSON API",
  },
  p3: {
    share: "Copy link to this plan", copied: "Link copied", print: "Print or save as PDF",
    briefT: "Landing brief", briefMission: "{n}-day mission",
  },
  m: {
    title: "Real Moon landings, replayed",
    intro: "Three robot landers have reached the Moon for NASA\u2019s CLPS program. Pick one, follow its story step by step, and watch the sky it really saw.",
    pick: "Missions",
    next: "Next", back: "Back", restart: "Start again", stepOf: "Step {n} of {total}", storyNav: "Story steps",
    quizT: "Can you guess?", right: "Yes, that\u2019s right!", wrong: "Not quite. Try another answer!",
    numbersT: "For curious minds: the numbers behind the story",
    way: { t: "On the way", d: "Two days before landing. {name} is still flying toward the Moon. Press Next to follow the story." },
    landed: "Landed", lastContact: "Last contact", toLanding: "Back to landing", slider: "Time through the mission",
    skyAlt: "The sky from the {name} landing site",
    stBefore: "Not landed yet", stOver: "Mission over",
    checkT: "What the model computes", checkH: "From the JPL table, for the real landing place and time. Green notes compare it with what the mission reported.",
    fSun: "Sun at touchdown", fEarth: "Earth at touchdown", fSunrise: "Sunrise before landing", fSunset: "Sunset after landing", fEclipse: "Sun fully behind Earth",
    above: "{x}° above the horizon",
    afterSunrise: "Touchdown came {d} after sunrise",
    endAfter: "Last contact came {d} after this sunset", endBefore: "The mission ended {d} before this sunset",
    eclipseNote: "Blue Ghost photographed this eclipse from the surface",
    showsT: "What the replay shows",
    smooth: "These three sites are computed on a smooth Moon: their local hills and craters are not in the model.",
    src: "Landing times, places and outcomes are from NASA and the mission teams\u2019 public reports.",
    open: "Open this place in the Planner",
    im1: {
      tag: "Landed, leaning",
      what: "Odysseus made the first US soft landing on the Moon since Apollo 17 in 1972, and the first by a private company. A leg broke at touchdown and it came to rest leaning about 30°. It worked for about a week.",
      shows: "At touchdown the Sun was {sun}° up and Earth {earth}° up, so this spot had both power and a radio link. The model puts sunset several days after the mission ended: leaning over, Odysseus lost light on its solar panels before the Sun actually set.",
      story: {
        land: { t: "A bumpy landing", d: "Odysseus came down too fast. A leg broke and it ended up leaning over, like a tent with a bent pole." },
        lean: { t: "Working while leaning", d: "Even tipped over, Odysseus sent pictures and science home. But its solar panels were not pointing the way they should." },
        end: { t: "Out of light", d: "The Sun kept moving around the sky until its light no longer reached the panels. After about a week, Odysseus ran out of power." },
        set: { t: "The real sunset", d: "Only now does the Sun really set here. Odysseus lost its light early because it was leaning, not because night came." },
      },
      quiz: {
        q: "Odysseus tipped over. Why was that a big problem?",
        a: ["Its solar panels could not face the Sun properly", "Robots get dizzy", "The Moon is too slippery to stand on"],
        why: "A lander needs its panels in the sunlight to make power. Leaning over, Odysseus lost its light days before the real sunset.",
      },
    },
    bg1: {
      tag: "Full success",
      what: "Blue Ghost made the first fully successful commercial Moon landing. It worked through a whole lunar day, about 14 Earth days, and for a few hours into the night.",
      shows: "The model has the Sun rising at the site a few hours before touchdown and setting on the evening of 16 March 2025, the same evening Blue Ghost sent its last data. It also shows the Sun slipping fully behind Earth on 14 March, which is the eclipse Blue Ghost photographed.",
      story: {
        rise: { t: "Sunrise on the Moon", d: "The Sun has just come up over the landing place. Blue Ghost wants to land in the morning, so it has a whole Moon day of sunlight ahead." },
        land: { t: "Touchdown!", d: "Blue Ghost lands upright on its four legs. The Sun gives it power and Earth is high in the sky, so it can talk to home." },
        eclipse: { t: "Earth hides the Sun", d: "Earth slides in front of the Sun for a few hours. From the Moon that is a solar eclipse, and Blue Ghost took a photo of it." },
        set: { t: "The Sun goes down", d: "After two weeks of daylight, night begins. A night on the Moon lasts two weeks too, and it is colder than anywhere on Earth." },
        end: { t: "Good night, Blue Ghost", d: "It kept working on its battery for a few more hours, then went quiet. Its job was done: a complete success!" },
      },
      quiz: {
        q: "Blue Ghost worked perfectly. So why did it stop after two weeks?",
        a: ["It ran out of rocket fuel", "The Sun set and the long, cold night began", "It flew back to Earth"],
        why: "Blue Ghost ran on sunlight. When the two-week night began it had no power left to keep warm. That was the plan all along.",
      },
    },
    im2: {
      tag: "Landed on its side",
      what: "Athena landed closer to the south pole than any lander before it, about 250 m from its target on Mons Mouton. It came to rest on its side inside a small crater, could not recharge, and the mission ended the next day.",
      shows: "At touchdown the Sun was only {sun}° above the horizon. That low, a crater wall is enough to put a lander in shadow, and on its side in a crater Athena had no way to recharge. This is why the Planner counts every degree of skyline.",
      story: {
        land: { t: "Closest to the south pole", d: "Athena lands nearer the Moon\u2019s south pole than any lander before. See how low the Sun is: only {sun}° above the ground." },
        side: { t: "On its side in a crater", d: "Athena tipped onto its side inside a small crater. With the Sun so low, the crater wall blocked the light like a tall fence." },
        end: { t: "Battery empty", d: "With no sunlight on its panels, Athena could not recharge. The mission ended the next day." },
      },
      quiz: {
        q: "The Sun was only {sun}° high where Athena landed. What can block a Sun that low?",
        a: ["Clouds", "Nothing at all", "A crater wall or even a small hill"],
        why: "The Moon has no clouds. But near the pole the Sun is so low that any bump on the ground can hide it, so planners check the skyline in every direction.",
      },
    },
  },
  l3: {
    help: "Pick a site to see its sky. Slide the bar to look up to 30 days ahead.",
    count: "of {m} sites can run a lander", now: "right now", at: "in {d}",
    pick: "Landing sites",
    skyAlt: "The sky from {site}: where the Sun and Earth are above or below the horizon.",
    below: "below the horizon", hill: "hidden by terrain",
    sunOn: "In sunlight. The solar panels are charging.", sunOff: "No sunlight. Running on battery.", sunBlocked: "The Sun is up, but hills or a crater wall hide it.",
    sunEnds: "Sunlight ends in about {d}", sunBack: "Sunlight returns in about {d}",
    earthOn: "Earth is in view. The radio works.", earthOff: "Earth is hidden. No contact with home.",
    earthEnds: "Earth sets in about {d}", earthBack: "Earth rises in about {d}",
    noChange: "Stays this way for the rest of the 30 days",
    share: "Power and signal together, over these 30 days",
    details: "Full details", plan: "Plan a landing here",
    play: "Play 30 days", pause: "Pause", reset: "Back to now", slider: "Time, from now to 30 days ahead",
    legSun: "Sunlight", legEarth: "Earth in view", end: "in {d}",
  },
  s2: {
    monthH: "Above 0° means visible from the site.",
    movedNote: "Real terrain from NASA LOLA. Placed on the LOLA peak of light, {m} m from the published point (different maps put the peak in slightly different places).",
    yearT: "Next 12 months", yearH: "Share of the year with sunlight, Earth, and both.",
    eventsH: "Next sunrises, sunsets and Earth-sets (UTC).",
  },
  g2: {
    intro: "Keep a small lander alive near the Moon\u2019s south pole. The Sun charges it, the cold drains it, and it can only send data while Earth is up.",
    go: "Keep going",
    tip: {
      ok: "All good! Watch the forecast to see when the Sun goes down.",
      send: "Science is flying home to Earth!",
      sci: "The battery looks good. Turn science on!",
      radio: "Earth is up! Turn on the radio to send your science home.",
      full: "Memory is full. Switch science off until Earth comes back.",
      dark: "It\u2019s dark and cold. Hibernate to save your battery!",
      low: "Battery is low! Switch things off or hibernate.",
      sleep: "Shh\u2026 saving power until the Sun comes back.",
      wake: "Lots of sunshine! Wake up and do some science.",
      frozen: "Brrr\u2026 the battery ran out.",
    },
    bandHi: "Meet your lander",
    sndOn: "Sound on", sndOff: "Sound off",
    share: "Share my score", copied: "Copied",
    shareText: "Race the Shadow, daily challenge {day}: {mb} MB sent home {stars}",
    aiNote: "The mission pictures, the scene above and the loading picture are AI-generated illustrations, not real photos. Everything the game calculates comes from real NASA JPL data.",
    x: {
      title: "Why is the south pole tricky?", sub: "Tap the numbered dots to find out.",
      alt: "Illustration of the Moon\u2019s south pole: the Sun on the horizon, Earth low in a black sky, a bright ridge and a deep dark crater.",
      sun: { t: "The Sun stays low", d: "At the pole the Sun never climbs high. It slides along the horizon, so even a small hill can hide it for days." },
      earth: { t: "Earth is the only phone line", d: "A lander talks to home by radio. When Earth dips below the horizon, the messages stop until it comes back." },
      ridge: { t: "High ground gets more light", d: "Ridges and crater rims poke up into the sunshine. Some are lit almost all year, which is perfect for solar panels." },
      shadow: { t: "Very long shadows", d: "With the Sun so low, even a small rock casts a shadow far longer than itself. A lander stuck in one cannot charge its battery." },
      crater: { t: "Craters that never see the Sun", d: "The floors of some craters have been dark for billions of years. They are among the coldest places we know, and may hide frozen water." },
    },
  },
  a: {
    title: "Ask Hyphen AI",
    intro: "Hyphen AI is a robot guide who knows the Moon\u2019s south pole. Ask her about the Sun, Earth, landers, or where to land. For sky questions she looks up the same real NASA data as the Planner.",
    hello: "Hi, I\u2019m Hyphen AI! What would you like to know about the Moon\u2019s south pole?",
    tryT: "Not sure what to ask? Tap one:",
    qs: ["Why is it so hard to land at the Moon\u2019s south pole?", "Which landing sites have sunlight right now?", "Where is the best place to land next month?",
         "Why did the Athena lander stop working?", "How long is a night on the Moon?", "Why does a lander need to see Earth?"],
    close: "Close", tease: "Hi! Ask me about the Moon \ud83c\udf19",
    inputLabel: "Your question", placeholder: "Type your question here\u2026", send: "Ask", clear: "Start over",
    thinking: "Hyphen AI is looking at the sky\u2026", checked: "Hyphen AI checked the real NASA sky data",
    errSetup: "Hyphen AI is not switched on yet. Whoever runs this site needs to add an API key.",
    errOffline: "Hyphen AI needs the internet to answer. Check your connection and ask again.",
    errBusy: "So many questions at once! Wait a minute, then ask again.",
    errRefused: "Hyphen AI can\u2019t help with that one. Try a question about the Moon!",
    errOther: "Something went wrong. Please ask again.",
    note: "Hyphen AI is an AI and can make mistakes. Her Sun and Earth numbers come from the same NASA JPL data as the Planner. Please don\u2019t type your name, school or address.",
  },
  g3: {
    howT: "How to play", howSub: "You are mission control for a small Moon lander. Four things to know:",
    steps: [["Sunlight fills the battery", "When the Sun is up, the solar panels charge the battery. In the dark, the cold drains it."],
            ["Science collects data", "Switch Science ON to gather data. It uses power, and the memory can fill up."],
            ["The radio sends it home", "Switch Radio ON while Earth is up. Every MB that reaches Earth counts toward your score."],
            ["Hibernate through the dark", "Fill the battery before the Sun sets. Then press Hibernate to sleep until sunrise."]],
    win: "You win by reaching the mission goal.", lose: "You lose if the battery drops to 0%.",
    keys: "The game stops at every alert so you have time to decide. The forecast under the picture shows when the Sun and Earth will be up. Change the speed with ▶ ▶▶ ▶▶▶, or press the space bar to pause.",
    goal: "Your goal", start: "Start the mission", resume: "Back to the mission",
  },
  w: {
    title: "Why it\u2019s hard",
    help: "Same Sun, same Earth. Only where the lander stands changes. Switch places and watch one Moon day.",
    canvasLabel: "A lander on the lunar south pole with the Sun and Earth moving along the horizon",
    where: "Where the lander stands", ridge: "On a ridge", crater: "In a crater",
    pOn: "Power on", pOff: "No power", rOn: "Radio on", rOff: "No radio",
    msgBoth: "Sunlight and Earth in view: the lander can work.",
    msgNoSun: "The Sun is behind the skyline: no power, the lander freezes.",
    msgNoEarth: "Earth has dropped below the skyline: no radio contact.",
    msgNone: "No Sun and no Earth: the lander must sleep and wait.",
    day: "Moon day \u00b7 day {d} of 30",
    tally: "Over this Moon day",
    tPower: "power", tRadio: "radio",
    note: "Real Sun and Earth positions from NASA JPL for the coming Moon day. Skylines are illustrative; heights are exaggerated \u00d7{k}.",
    photoT: "The real south pole, from orbit",
    photoD: "This is an actual photo mosaic from NASA\u2019s Lunar Reconnaissance Orbiter. The pole is at the centre. Black patches are crater floors the Sun never reaches; bright rims catch light for most of the year. That contrast is exactly what a mission has to plan around.",
    photoPin: "Shackleton crater (the pole)",
    photoDark: "Always in shadow",
    photoCredit: "Image: NASA/GSFC/Arizona State University, LROC WAC south pole mosaic",
  },
  p: {
    kicker: "NASA Space Apps 2026 · CLPS Lunar Mission Browser",
    question: 'Where and when can a lander near the Moon’s south pole get <b>sunlight for power</b> and <em>see Earth to talk home</em>?',
    step1: "Pick a site on the polar map", step2: "Choose the dates", step3: "Read the verdict and press Play",
    setup: "Mission setup",
    mapTitle: "South polar map",
    mapSub: "Looking down on the pole. Each ring fills with the share of time a site has power and signal together.",
    mapEarth: "toward Earth", mapSunNow: "Sun direction now",
    dropPin: "Drop a pin", dropHint: "Click the map to add a site there", cancel: "Cancel",
    offMap: "off map",
    pickSite: "Landing site", pickDates: "Dates", startDate: "Start date", howLong: "How long",
    opt14: "2 weeks", opt29: "1 Moon day (29.5 days)", opt60: "2 months", opt180: "6 months", opt365: "1 year",
    dateHint: "One Moon day lasts about 29.5 Earth days. At the pole, seasons also change how much sunlight reaches the ground over the year.",
    advanced: "Advanced settings", missionLen: "Mission length (days)", missionHint: "Used to rank the best days to land.",
    maskLbl: "Earth must be at least this high (°)", maskHint: "Antennas often need Earth a few degrees above the horizon. 0 means just above it.",
    horizonLbl: "Ground shape around the site", hSmooth: "Smooth Moon (no mountains)", hRaised: "Site on a hill (enter height)", hTerrain: "Real terrain from NASA LOLA (load file)",
    metres: "metres above the plains", loadCsv: "Load a terrain file (CSV from horizon_mask.py)",
    csvBad: "Couldn't read a horizon from that file. Expected lines of azimuth_deg,horizon_deg.",
    csvFar: "Loaded, but this file was made for {lat}, {lon}, not {site}.",
    addSite: "Add a site by coordinates", latlonHint: "Latitude, longitude in degrees. South is negative, west is negative.", addBtn: "Add site", custom: "My site",
    ground: "Ground and mountains", sky: "sky",
    skyTitle: "What you'd see standing there",
    skySub: "A full turn around you, north back to north. The grey shape is the ground; anything above it is visible. Faint dots trace the Sun and Earth over the whole period.",
    hSmoothS: "smooth Moon", hRaisedS: "on a {h} m hill", hTerrainS: "real terrain",
    play: "Play", pause: "Pause", speed: "Speed", time: "Time",
    sunUp: "Sun is up", sunUpN: "solar panels are charging", sunPart: "Sun is partly hidden", sunPartN: "{p}% of the Sun is visible", sunDown: "Sun is down", sunDownN: "running on batteries",
    earthUp: "Earth is visible", earthUpN: "can send data home", earthDown: "Earth is hidden", earthDownN: "no signal to Earth",
    tlTitle: "Over the whole period",
    tlSub: "Lines above zero mean the Sun or Earth is visible. The bars below show when the lander has power, a signal, or both. Click or drag to move through time.",
    yAxis: "degrees above horizon", bPower: "Power", bSignal: "Signal", bBoth: "Both",
    cmpTitle: "Compare landing sites", cmpSub: "Same dates for every site. Click a row to open it, click a heading to sort.",
    cSite: "Site", cSun: "Sunlight", cDark: "Longest dark", cEarth: "Earth in view", cBoth: "Both", cPub: "Published",
    pubHint: '“Published” is a long-term sunlight figure from studies that include real mountains (<a href="https://en.wikipedia.org/wiki/Peak_of_eternal_light" target="_blank" rel="noopener">summary</a>). A big gap from our smooth-Moon number shows how much the terrain matters.',
    winTitle: "Best times to land",
    winSub: "For a {n}-day mission at {site}. Higher % means more time with power and a signal at the same time.",
    winWorst: "longest time without both: {d}", winSc: "power + signal",
    winNone: "No landing time in these dates has the Sun and Earth up together here. Try longer dates, another site, or lower the Earth height in Advanced settings.",
    kSun: "Sunlight (power)", kSunN: "of the time", kDark: "Longest dark stretch", kDarkN0: "Sun never sets", kDarkN: "in one go",
    kEarth: "Earth in view (signal)", kEarthN: "of the time", kBoth: "Power and signal together", kBothN: "of the time",
    vGreat: "Good place to land", vOk: "Possible, with planning", vHard: "Hard place to survive",
    vHeadGreat: "{site} looks good for these dates", vHeadOk: "{site} can work, but plan for gaps", vHeadHard: "{site} is tough for these dates",
    vSunAll: "The Sun never sets here in this period, so the solar panels always get light.",
    vSun: "The Sun is up {p}% of the time. The longest stretch of darkness is {d}.",
    vEarthAll: "Earth is always in view, so the lander can always send data home.",
    vEarthNone: "Earth never rises here in this period, so the lander can't talk home directly. It would need a relay satellite.",
    vEarth: "Earth is visible {p}% of the time, so the lander can talk home that often. The longest silence is {d}.",
    vWarn: "Warning: most small landers can't survive more than a few days without sunlight. The cold drains the batteries.",
    vTerrain: "This uses a smooth Moon with no mountains. Load real terrain in Advanced settings for a site-specific answer.",
    glossTitle: "Words used here",
    gloss: [["Horizon", "The line where the ground meets the sky. Mountains and crater rims make it higher in some directions."],
            ["Elevation", "How high something is above the flat horizon, in degrees. 0° is right on the horizon, 90° is straight up."],
            ["Direct-to-Earth link", "The lander talking to Earth by radio. It only works when Earth is above the horizon."],
            ["Moon day", "About 29.5 Earth days from one sunrise to the next. Away from the poles, that's roughly 2 weeks of light and 2 weeks of night."],
            ["Why the pole is special", "The Moon's axis is tilted only 1.5°, so at the pole the Sun circles around the horizon instead of rising high."],
            ["Libration", "The Moon wobbles slightly as it orbits, so from the pole Earth slowly bobs above and below the horizon."],
            ["LOLA", "A laser on NASA's Lunar Reconnaissance Orbiter that mapped the height of the whole Moon."],
            ["CLPS", "Commercial Lunar Payload Services: NASA pays companies to fly science to the Moon on their landers."]],
    howTitle: "How the numbers are calculated",
    notes: ["<b>Where the Sun and Earth are.</b> From NASA JPL's DE421 ephemeris, including the Moon's wobble (librations), turned into the Moon-fixed frame used by NASA's LOLA maps. Light travel time and the site's offset from the Moon's centre are included. The data covers 2024–2032 at 3-hour steps. The Moon orientation agrees with the independent IAU model to within 15 arcseconds.",
            "<b>Power.</b> Counted when at least half of the Sun's disk is above the horizon in the Sun's direction.",
            "<b>Signal.</b> Counted when Earth's centre is above the horizon plus the minimum height set in Advanced settings.",
            "<b>Ground shape.</b> Smooth Moon uses a perfect sphere. Site on a hill lowers the horizon the way it would for a peak above flat plains. Real terrain uses a skyline computed from NASA LOLA elevation maps with the included Python tool. Only real terrain captures shadows from crater rims.",
            "<b>Best times to land.</b> Every 6 hours in the chosen dates is tested as a landing time. The score is the share of the mission with power and signal together; ties go to the shorter worst gap. Landing needs the Sun and Earth both up.",
            "<b>Limits.</b> Site coordinates come from published studies and are approximate. Relay satellites, ground-station schedules, temperature and slope safety are not included."],
    gameCta: "Play Race the Shadow", gameCtaSub: "Keep a lander alive through the lunar night, on the same sky data.",
  },

  g: {
    tagline: "A lunar survival game running on real NASA JPL sky data",
    intro: "You run a small robotic lander near the Moon's south pole. <b>The Sun charges your battery, the cold drains it, and you can only send science home when Earth is above the horizon.</b> Every sunrise, sunset and Earth-set in this game comes from NASA JPL's real ephemeris for the dates you play.",
    scn: {
      vikram: { t: "Vikram's Night", d: "Hard", story: "In 2023, India's Vikram lander touched down near 69°S, did its science, and never woke up after its first lunar night. Your lander has survival heaters. Can it live through the dark?", goal: "Survive the 2-week night and wake up at sunrise." },
      tipped: { t: "Tipped Over", d: "Medium", story: "In 2025, a lander touched down on its side and its solar panels pointed the wrong way. Yours has landed crooked on Malapert Mountain. The panel only catches the Sun from one direction.", goal: "Send {g} MB of science home in 10 days." },
      peak: { t: "Peak of Light", d: "Open", story: "Be the mission planner. Pick a site on the south-pole ridges and a landing date anywhere in the next year, then fly a 14-day mission.", goal: "Send as much science home as you can in 14 days." },
      daily: { t: "Today\u2019s challenge", d: "Daily", story: "One new mission every day, the same for everyone: ten days, with a site and a date picked by the calendar. Beat your friends\u2019 score.", goal: "Send as much science home as you can in 10 days." },
    },
    best: "Your best: {v}", play: "Play",
    setupTitle: "Choose where and when to land", setupSub: "Real planners do exactly this. The forecast below shows the next 14 days of sunlight and Earth contact for your choice.",
    site: "Landing site", landDate: "Landing date (00:00 UTC)", back: "Back", launch: "Land here",
    pvTxt: "Next 14 days: Sun up {s}% of the time, Earth up {e}%, both together {b}%.",
    abort: "Quit mission", battery: "Battery", stored: "Science waiting", sent: "Sent to Earth", clock: "Mission time",
    fcTitle: "Forecast: next 5 days", fcSub: "from the real ephemeris", now: "now", dayN: "+{n}d",
    sci: "Science instruments", rad: "Radio to Earth", hib: "Hibernate", on: "ON", off: "OFF",
    sciS: "+{mb} MB/h · uses {w} W", radS: "{mb} MB/h · {w} W · needs Earth up", hibS: "Uses only {w} W. Science and radio stop.",
    radWait: "Waiting: Earth is below the horizon", radIdle: "Nothing to send yet",
    autoPause: "Pause on alerts", logTitle: "Mission log", pauseLbl: "Pause", spaceHint: "Space bar pauses and resumes",
    flowIn: "Solar in", flowOut: "Using", maxMb: "max {n} MB",
    day: "Day {d}", dayShort: "Day {d} · {h}:00",
    goal: "Goal", goalPeak: "send as much as you can in 14 days",
    exag: "heights exaggerated ×{k}", panel: "panel",
    ev: {
      land: "Touchdown! Systems are online.",
      sunsetSoon: "Sunset in about {h} hours. Is your battery full?",
      sunset: "The Sun has set. Heaters are on.",
      sunrise: "Sunrise! The panels are charging again.",
      earthsetSoon: "Earth sets in about {h} hours. Send your data now.",
      earthset: "Earth has set. No radio contact.",
      earthrise: "Earth is back above the horizon.",
      batLow: "Battery below 25%. Cut power or hibernate.",
      storeFull: "Memory full. New science is being lost.",
      frozen: "Battery empty. The lander froze.",
      done: "Mission complete.", hib: "Hibernating. Only survival heaters are on.", wake: "Waking up. Systems back online.",
    },
    win: "Mission success", lose: "Lander lost", done: "Mission complete",
    st: { sent: "Sent to Earth", lost: "Science lost (memory full)", minBat: "Lowest battery", dark: "Hours in darkness", survived: "Survived", hours: "{n} h" },
    replayCap: "Battery over the mission (amber = Sun up, blue = Earth up).",
    again: "Try again", other: "Other missions",
    why: {
      title: "Why did that happen?",
      vikramWin: "You entered the night with <b>{b}%</b> battery and hibernated. At {w} W, the survival heaters needed about <b>{need} Wh</b> to get through <b>{n} hours</b> of darkness.",
      vikramLose: "The night at this site lasted <b>{n} hours</b>. Awake, the lander uses {aw} W in the dark, so a full battery lasts only about <b>{last} hours</b>. Even hibernating, it needs about {need} Wh, so it must start the night nearly full.",
      vikramFact: "The real Vikram lander was designed for one lunar day, about 14 Earth days, and did not wake up after the night. Surviving the lunar night is one of the hardest problems for Moon landers.",
      tippedTxt: "Your panel faced {pa}°. Near the pole the Sun circles the whole horizon about once every 29.5 days, so it spent part of the mission behind your panel. Power came mostly when the Sun swung around toward it.",
      tippedLose: "Your lander ran everything while the panel was getting little or no light, and the battery emptied. Hibernate at first, and turn science on once the Sun swings round toward the panel.",
      tippedFact: "When a lander tips over, the solar panels can end up facing the ground or the wrong direction, and the mission may end early because the batteries can't recharge.",
      peakTxt: "At {site}, the Sun was up {s}% and Earth {e}% of your mission, both together {b}%. Sites high on crater rims and ridges catch more sunlight; Earth contact depends on the Moon's slow wobble.",
      peakFact: "Try the same site on a different date, or compare every site at once in the Planner.",
      data: "All Sun and Earth positions came from NASA JPL's DE421 ephemeris for your exact dates. The Moon is treated as smooth (no mountains), so real rim sites may do even better.",
      open: "Open this site in the Planner",
    },
  },

  adv: {
    kicker: "Astronaut training",
    title: "Fly to the <em>Moon</em>!",
    intro: "Pick your astronaut, suit up, choose a rocket and fly all the way from Earth to the Moon’s south pole.",
    mc: "Mission Control",
    you: "Commander {name}",
    step: "Step {n} of {total}",
    nameQ: "What should Mission Control call you?",
    namePh: "First name or nickname",
    nameNote: "Just a first name or nickname. It stays on this device and is never sent anywhere.",
    kidQ: "Who is flying to the Moon?",
    suitQ: "Choose your spacesuit",
    shipQ: "Choose your rocket",
    avatar: "Astronaut {n}",
    suits: { white: "Classic White", orange: "Rescue Orange", blue: "Future Blue" },
    suitsD: { white: "Like the suits astronauts wear on space walks.", orange: "Bright orange is easy to spot if you need help.", blue: "Glowing armour for the explorers of tomorrow." },
    ships: { rocket: "Red Comet", shuttle: "Star Shuttle", future: "Blue Arrow" },
    shipsD: { rocket: "A classic rocket with three round windows.", shuttle: "A space plane riding a giant fuel tank.", future: "A sleek rocket from the future." },
    next: "Next", back: "Back", go: "Start the mission!", ok: "OK!",
    suitUp: "Suiting up…",
    voice: "Read aloud", sound: "Sound", skip: "Skip", lang: "Language",
    noVoice: "This device has no English voice installed, so Mission Control will only show the words.",
    hold: "HOLD", fire: "FIRE", drop: "DROP", brake: "BRAKE", thrust: "THRUST", photo: "PHOTO", jump: "JUMP", plant: "PLANT FLAG",
    alt: "Height", speed: "Speed", kmh: "{n} km/h", ms: "{n} m/s", m: "{n} m", km: "{n} km",
    toMoon: "To the Moon", day: "Day {n}",
    found: "{n} of {total}",
    b: {
      hello: "Hello, future astronaut! I’m Mission Control. I’ll help you all the way to the Moon. First, what’s your name?",
      kid: "Nice to meet you, {name}! Tap the astronaut who is going on this trip.",
      suit: "Space has no air, and it’s super hot in the Sun and super cold in the shade. Your suit keeps you safe. Pick one!",
      ship: "Now pick your rocket! It has to go 11 kilometres every second to escape Earth’s gravity.",
      ready: "Crew ready! Commander {name}, are you ready to fly to the Moon?",
      pad: "You’re on the launch pad! Press and HOLD the big button to start the engines.",
      holdOn: "Keep holding… the engines are warming up!",
      liftoff: "LIFTOFF! Hold on tight, it’s very shaky!",
      sky: "The sky is getting darker. There’s less and less air up here.",
      stage: "The first fuel tank is empty! Tap DROP to let it go and make the rocket lighter.",
      orbit: "We’re in orbit! We fly all the way around Earth in about 90 minutes. Drag the screen to look around!",
      tli: "The Moon is 384,000 kilometres away. Tap FIRE to point us at the Moon!",
      water: "Zero gravity! Water floats in wobbly balls up here. Tap the water balls to drink them!",
      waterDone: "Slurp! Astronauts really drink their water this way.",
      rocks: "Uh-oh, space rocks ahead! Tap them to push them out of the way!",
      rocksDone: "Phew! Great flying, {name}!",
      gaze: "{name} floats over to the window and presses their nose to the glass…",
      galaxy: "Wow! That glowing river of stars is our galaxy, the Milky Way. It holds more than 100 billion stars, and our Sun is just one of them!",
      lookBack: "Look back! Earth is getting smaller and smaller. The trip to the Moon takes about 3 days.",
      wave: "Tap Earth to wave goodbye!",
      waved: "Bye-bye, Earth! See you soon!",
      brake: "We’re at the Moon! Hold BRAKE to slow down, so the Moon’s gravity can catch us.",
      earthrise: "Wow, look! Earth is rising over the Moon. Tap PHOTO to take a picture!",
      photo: "Amazing photo! It’s going on your certificate.",
      lander: "Time to land! Your lander leaves the rocket. You fly it now!",
      landHow: "The Moon pulls you down. Hold THRUST to slow down, and touch down gently!",
      tooFast: "Too fast! Hold THRUST!",
      bumpy: "Bumpy landing, but everyone is OK! Phew!",
      touchdown: "Touchdown! You landed near the Moon’s south pole! Super soft landing!",
      pole: "Here at {site} the Sun stays low on the horizon, so shadows are super long. Ice hides in dark craters that never see sunlight!",
      live: "The Sun and Earth in your sky are where they really are at this spot right now.",
      walk: "Time for a moonwalk! Tap JUMP. You weigh 6 times less on the Moon, so you can jump really high!",
      jumped: "Wheee! Look at that jump!",
      flag: "Pick a flag to plant on the Moon.",
      plantHow: "Tap PLANT FLAG to push the pole into the Moon dust!",
      noWind: "There’s no wind on the Moon, so real Moon flags have a rod at the top to hold them open!",
      peace: "Nobody owns the Moon: it belongs to everyone. So we’ll leave a message for all humankind.",
      done: "Mission complete, Commander {name}! Salute!",
    },
    flagQ: "Choose your flag", flagSearch: "Search for a country", flagNone: "No country found",
    plaque: "Here {name} from planet Earth set foot near the south pole of the Moon. We came in peace for all humankind.",
    cert: {
      title: "Moon Landing Certificate", line: "This certifies that", did: "flew from Earth to the Moon and landed near the lunar south pole.",
      date: "Date", ship: "Rocket", site: "Landing site", signed: "Mission Control",
      download: "Download certificate", again: "Fly again", home: "Back to Hyphen", game: "Next: keep your lander alive in Race the Shadow",
    },
    lite: "Your device is busy, so we switched to simpler 3D.",
    no3d: "This device can’t show the 3D part of the mission. Try another browser or computer.",
  },
};

export type Dict = typeof en;

const bn: Dict = {
  brand: "হাইফেন", tagline: "মিশন মুনলাইট",
  nav: { home: "সারসংক্ষেপ", planner: "প্ল্যানার", game: "ছায়ার সাথে দৌড়", missions: "মিশন", ask: "হাইফেন এআই-কে জিজ্ঞেস করো", adv: "চাঁদের অ্যাডভেঞ্চার" },
  theme: { toLight: "হালকা থিমে যাও", toDark: "গাঢ় থিমে যাও" },
  loading: "JPL ephemeris লোড হচ্ছে…",
  loadFail: "আকাশের ডেটা লোড হয়নি। আবার চেষ্টা করতে পেজটা রিলোড করো।",
  footer: "সূর্য আর পৃথিবীর অবস্থান: NASA JPL DE421 ephemeris, চাঁদের দোলন সহ · চাঁদের ME ফ্রেম · সব সময় UTC-তে · NASA Space Apps 2026, CLPS Lunar Mission Browser চ্যালেঞ্জের জন্য তৈরি",
  compass: ["N", "NE", "E", "SE", "S", "SW", "W", "NW", "N"],
  utc: "UTC",
  sun: "সূর্য", earth: "পৃথিবী",
  days: "{n} দিন", day1: "১ দিন", hours: "{n} ঘণ্টা", hour1: "১ ঘণ্টা", zero: "নেই",

  l: {
    kicker: "লাইভ · NASA JPL DE421 ephemeris",
    title: "চাঁদের একদম নিচে <em>আলোর</em> পিছু নাও।",
    lede: "চাঁদের দক্ষিণ মেরুতে সূর্য কখনো এক-দুই ডিগ্রির বেশি ওঠে না। সে দিগন্ত ঘিরে ঘোরে আর গর্তের কিনারায় কয়েক দশ কিলোমিটার লম্বা ছায়া টেনে নেয়। কোথায় আর কবে নামবে বেছে নাও, আর দেখো ঠিক কখন ল্যান্ডার বিদ্যুৎ পাবে আর বাড়ির সাথে যোগাযোগ রাখতে পারবে।",
    ctaPlanner: "প্ল্যানার খোলো", ctaGame: "ছায়ার সাথে দৌড় খেলো",
    f1: "চাঁদের অক্ষের হেলানো", f2: "এক সূর্যোদয় থেকে পরেরটা", f3: "আকাশে পৃথিবীর দোলন",
    sunAtPole: "মেরুর উপরে সূর্য", sitesLit: "আলোয় থাকা সাইট", speed: "{n} দিন/সে",
    terrainNote: "ভূখণ্ড আনুমানিক। দেখানো সময়ের সূর্য আর পৃথিবীর দিক আসল। সময় বদলাতে টেনে নাও।",
    liveKicker: "এই মুহূর্তে চাঁদে", liveTitle: "{total}টার মধ্যে {n}টা সাইটে বিদ্যুৎ আর পৃথিবীর সাথে যোগাযোগ আছে",
    sunUp: "সূর্য উঠে আছে", sunDown: "সূর্য ডুবে আছে", earthUp: "পৃথিবী দেখা যায়", earthDown: "পৃথিবী আড়ালে", details: "বিস্তারিত",
    needKicker: "সমস্যাটা", needTitle: "মেরুর ল্যান্ডারের একসাথে দুটো জিনিস লাগে",
    powerTag: "বিদ্যুৎ", powerTitle: "প্যানেলে সূর্যের আলো",
    powerText: "সূর্য দিগন্ত ছুঁয়ে যায়, তাই কয়েক কিলোমিটার দূরের একটা পাহাড়ও তাকে দিনের পর দিন ঢেকে রাখতে পারে। গর্তের তলায় রাত কয়েক সপ্তাহ; উঁচু কিনারা বছরের বেশিরভাগ সময় আলোয় থাকতে পারে।",
    linkTag: "যোগাযোগ", linkTitle: "দিগন্তের উপরে পৃথিবী",
    linkText: "মেরু থেকে পৃথিবী আকাশে নিচু হয়ে থাকে আর চাঁদের দোলনে ধীরে ধীরে ওঠানামা করে। দিগন্তের নিচে নামলে রিলে ছাড়া ল্যান্ডার বাড়িতে কথা বলতে পারে না।",
    toolKicker: "প্ল্যানার", toolTitle: "মিশন প্ল্যানারের যা লাগে, সব এক পর্দায়",
    next30: "পরের ৩০ দিন · {site}",
    tools: {
      compare: { t: "সাইট পাশাপাশি তুলনা", d: "একই তারিখে প্রতিটা সাইটের সূর্যের আলো, লম্বা রাত, পৃথিবী দেখা আর দুটো একসাথে থাকার সময়।" },
      scrub: { t: "সাইটে দাঁড়িয়ে Play চাপো", d: "৩৬০° দিগন্তে ঘণ্টায় ঘণ্টায় সূর্য আর পৃথিবীর চলাচল।" },
      windows: { t: "নামার সেরা সময় খোঁজো", d: "প্রতি ৬ ঘণ্টা নামার সময় হিসেবে পরীক্ষা হয়; বিদ্যুৎ আর সিগন্যাল একসাথে ধরে সেরাগুলো সাজানো।" },
      terrain: { t: "আসল LOLA ভূখণ্ড আনো", d: "NASA উচ্চতার ম্যাপ থেকে বানানো দিগন্ত লোড করো, সব সংখ্যা আসল দিগন্ত ধরে বদলে যাবে।" },
    },
    gameKicker: "ক্লাসরুম আর কৌতূহলীদের জন্য", gameTitle: "ছায়ার সাথে দৌড়",
    gameText: "চন্দ্র-রাত পার করে একটা ছোট ল্যান্ডার বাঁচিয়ে রাখো। গেমের প্রতিটা সূর্যোদয় আর পৃথিবী-অস্ত একই আসল ephemeris থেকে।",
    apiKicker: "ডেভেলপারদের জন্য", apiTitle: "একই সংখ্যা, JSON হিসেবে",
    apiText: "এখানকার প্রতিটা পেজ সার্ভারে DE421 টেবিল থেকে হিসাব করা। যেকোনো সাইট বা অক্ষাংশ-দ্রাঘিমাংশ জিজ্ঞেস করো।",
  },
  s: {
    back: "সারসংক্ষেপ", kicker: "ল্যান্ডিং সাইট", open: "প্ল্যানারে খোলো", pub: "ভূখণ্ড-গবেষণায় দীর্ঘমেয়াদে {p}% আলো",
    now: "এই মুহূর্তে", monthKicker: "পরের ৩০ দিন", monthTitle: "দিগন্তের উপরে সূর্য আর পৃথিবী",
    eventsTitle: "সামনে যা আসছে", noEvents: "পরের ৩০ দিনে কোনো সূর্যোদয়, সূর্যাস্ত, পৃথিবী-উদয় বা পৃথিবী-অস্ত নেই।",
    yearTitle: "পরের ১২ মাস", others: "অন্য সাইট",
    ev: { sunrise: "সূর্যোদয়", sunset: "সূর্যাস্ত", earthrise: "পৃথিবী ওঠে", earthset: "পৃথিবী ডোবে" },
  },
  p2: {
    title: "অবতরণের পরিকল্পনা",
    intro: "সাইট আর তারিখ বেছে নাও। দেখো কখন ল্যান্ডার বিদ্যুতের জন্য সূর্যের আলো পায় আর ডেটা পাঠাতে পৃথিবী দেখতে পায়।",
    s1: "ল্যান্ডিং সাইট বেছে নাও", s1h: "মানচিত্রের বিন্দুতে বা তালিকার নামে চাপো।",
    listHead: "বিদ্যুৎ + সিগন্যাল",
    s2: "তারিখ বেছে নাও", s2h: "ল্যান্ডার কখন সেখানে থাকবে?",
    s3: "ফলাফল",
    vGreat: "নামার জন্য ভালো", vOk: "পরিকল্পনা করলে চলবে", vHard: "ঝুঁকিপূর্ণ",
    bodyGreat: "প্রচুর সূর্যের আলো আর পৃথিবীর সাথে নিয়মিত যোগাযোগ।",
    bodyOk: "বিদ্যুৎ বা রেডিও যোগাযোগে বিরতি আশা করো।",
    bodyHard: "লম্বা অন্ধকার সময় বা পৃথিবীর সাথে খুব কম যোগাযোগ।",
    warn: "এখানে রাত ৪ দিনের বেশি। বেশিরভাগ ছোট ল্যান্ডার জমে যায়।",
    cSun: "সূর্যের আলো", cDark: "সবচেয়ে লম্বা রাত", cEarth: "পৃথিবী দেখা যায়", cBoth: "বিদ্যুৎ + সিগন্যাল",
    skyT: "সাইটের চারপাশ দেখো", skyH: "Play চাপো, আকাশে সূর্য আর পৃথিবীর চলাচল দেখো। ধূসর অংশটা মাটি।",
    tlT: "পুরো সময় এক নজরে", tlH: "০° এর উপরে মানে দেখা যায়। বারগুলো বিদ্যুৎ, সিগন্যাল বা দুটোই দেখায়। সময় বদলাতে টেনে নাও।",
    cmpT: "সব সাইট তুলনা", cmpH: "সব সাইটের জন্য একই তারিখ। বদলাতে কোনো সারিতে চাপো।",
    winT: "নামার সেরা সময়", winH: "{n} দিনের মিশনের জন্য সেরা শুরুর সময়।",
    winGap: "সবচেয়ে লম্বা বিরতি: {d}",
    more: "আরও জানো: শব্দ আর পদ্ধতি",
    smoothChip: "মসৃণ", smoothTip: "এই সাইটের ভূখণ্ড-ডেটা নেই: মসৃণ চাঁদ ধরে হিসাব",
    terrainOn: "আসল পাহাড়-পর্বত ধরা হয়েছে: NASA LOLA উচ্চতা-ডেটা থেকে দিগন্ত।",
    terrainOff: "মসৃণ চাঁদ: এখানে ভূখণ্ড-ডেটা নেই, তাই পাহাড় ধরা হয়নি।",
    terrainRaised: "সহজ পাহাড় মডেল (সমতল থেকে {h} মিটার উঁচু), আসল ভূখণ্ড না।",
    pubTip: "আসল পাহাড়-পর্বত ধরে করা গবেষণায় দীর্ঘমেয়াদি আলো",
  },
  l2: {
    lede: "চাঁদের দক্ষিণ মেরুতে সূর্য প্রায় ওঠেই না। খুঁজে বের করো কোথায় আর কবে ল্যান্ডার আলো পায় আর পৃথিবী দেখতে পায়।",
    liveT: "এই মুহূর্তে চাঁদে", liveH: "NASA JPL ডেটা থেকে লাইভ। সূর্যের আলো আর পৃথিবী দুটোই থাকলে সাইট প্রস্তুত।",
    colSite: "সাইট", colSun: "সূর্যের আলো", colEarth: "পৃথিবী", colStatus: "অবস্থা",
    ready: "প্রস্তুত", noPower: "বিদ্যুৎ নেই", noSignal: "সিগন্যাল নেই", offline: "অন্ধকার আর নীরব",
    up: "উঠে আছে", down: "ডুবে আছে", visible: "দেখা যায়", hidden: "আড়ালে",
    whyT: "কেন কঠিন", whyH: "ল্যান্ডারের একই সময়ে এই দুটো লাগে।",
    powerT: "বিদ্যুতের জন্য সূর্যের আলো", powerD: "সূর্য দিগন্ত ছুঁয়ে যায়, তাই কাছের একটা পাহাড় দিনের পর দিন তাকে ঢেকে রাখতে পারে।",
    linkT: "রেডিওর জন্য পৃথিবী দেখা", linkD: "পৃথিবী আকাশে নিচু থাকে আর ধীরে ধীরে দিগন্তের নিচে নামে-ওঠে।",
    howT: "কীভাবে অবতরণ পরিকল্পনা করবে", howH: "প্ল্যানারে তিনটা ধাপ।",
    h1: "সাইট বেছে নাও", h1d: "মেরুর মানচিত্রে একটা জায়গায় চাপো।",
    h2: "তারিখ বেছে নাও", h2d: "ল্যান্ডার কবে পৌঁছাবে ঠিক করো।",
    h3: "ফলাফল পড়ো", h3d: "বিদ্যুৎ, সিগন্যাল আর নামার সেরা সময় দেখো।",
    gameT: "খেলে শেখো", gameD: "একই আসল আকাশের ডেটায় চন্দ্র-রাত পার করে ল্যান্ডার বাঁচিয়ে রাখো।",
    api: "ডেভেলপারদের জন্য: JSON API",
  },
  p3: {
    share: "এই পরিকল্পনার লিংক কপি করো", copied: "লিংক কপি হয়েছে", print: "প্রিন্ট করো বা PDF হিসেবে রাখো",
    briefT: "অবতরণের সারপত্র", briefMission: "{n} দিনের মিশন",
  },
  m: {
    title: "আসল চাঁদে অবতরণ, আবার দেখো",
    intro: "NASA-র CLPS কর্মসূচিতে এ পর্যন্ত তিনটা রোবট ল্যান্ডার চাঁদে পৌঁছেছে। একটা বেছে নাও, ধাপে ধাপে তার গল্প দেখো, আর সে আসলে যে আকাশ দেখেছিল তা দেখো।",
    pick: "মিশন",
    next: "পরের ধাপ", back: "আগের ধাপ", restart: "আবার শুরু", stepOf: "ধাপ {n} / {total}", storyNav: "গল্পের ধাপ",
    quizT: "বলো তো দেখি?", right: "হ্যাঁ, একদম ঠিক!", wrong: "ঠিক হলো না। আরেকটা উত্তর বেছে দেখো!",
    numbersT: "কৌতূহলীদের জন্য: গল্পের পেছনের সংখ্যা",
    way: { t: "পথে আছে", d: "অবতরণের দুই দিন আগে। {name} এখনো চাঁদের দিকে উড়ে চলেছে। গল্পটা দেখতে “পরের ধাপ” চাপো।" },
    landed: "অবতরণ", lastContact: "শেষ যোগাযোগ", toLanding: "অবতরণের সময়ে ফেরো", slider: "মিশনের সময় ধরে",
    skyAlt: "{name}-এর অবতরণ-স্থান থেকে আকাশ",
    stBefore: "এখনো নামেনি", stOver: "মিশন শেষ",
    checkT: "মডেল যা হিসাব করে", checkH: "JPL-এর টেবিল থেকে, অবতরণের আসল জায়গা আর সময়ের জন্য। সবুজ লেখাগুলো মিশনের রিপোর্টের সাথে তুলনা।",
    fSun: "অবতরণের সময় সূর্য", fEarth: "অবতরণের সময় পৃথিবী", fSunrise: "অবতরণের আগের সূর্যোদয়", fSunset: "অবতরণের পরের সূর্যাস্ত", fEclipse: "সূর্য পুরোপুরি পৃথিবীর আড়ালে",
    above: "দিগন্তের {x}° উপরে",
    afterSunrise: "সূর্যোদয়ের {d} পরে অবতরণ",
    endAfter: "এই সূর্যাস্তের {d} পরে শেষ যোগাযোগ", endBefore: "এই সূর্যাস্তের {d} আগে মিশন শেষ",
    eclipseNote: "Blue Ghost চাঁদের মাটি থেকে এই গ্রহণের ছবি তুলেছিল",
    showsT: "রিপ্লে যা দেখায়",
    smooth: "এই তিনটা সাইট মসৃণ চাঁদ ধরে হিসাব করা: আশপাশের পাহাড় আর গর্ত মডেলে নেই।",
    src: "অবতরণের সময়, জায়গা আর ফলাফল NASA আর মিশন দলের প্রকাশিত রিপোর্ট থেকে নেওয়া।",
    open: "এই জায়গা প্ল্যানারে খোলো",
    im1: {
      tag: "হেলে নেমেছে",
      what: "Odysseus ছিল ১৯৭২ সালের Apollo 17-এর পর যুক্তরাষ্ট্রের প্রথম সফল চন্দ্র-অবতরণ, আর কোনো বেসরকারি কোম্পানির প্রথম। নামার সময় একটা পা ভেঙে যায় আর ল্যান্ডার প্রায় ৩০° হেলে থাকে। এটা প্রায় এক সপ্তাহ কাজ করেছিল।",
      shows: "অবতরণের সময় সূর্য ছিল {sun}° উপরে আর পৃথিবী {earth}° উপরে, তাই এই জায়গায় বিদ্যুৎ আর রেডিও যোগাযোগ দুটোই ছিল। মডেল অনুযায়ী সূর্যাস্ত হয়েছে মিশন শেষ হওয়ার কয়েক দিন পরে: হেলে থাকায় সূর্য ডোবার আগেই Odysseus-এর সোলার প্যানেলে আলো পড়া বন্ধ হয়ে যায়।",
      story: {
        land: { t: "ঝাঁকুনি দিয়ে নামা", d: "Odysseus খুব জোরে নেমেছিল। একটা পা ভেঙে যায় আর সে হেলে পড়ে, ঠিক যেন খুঁটি বেঁকে যাওয়া তাঁবু।" },
        lean: { t: "হেলে থেকেও কাজ", d: "হেলে থেকেও Odysseus ছবি আর বিজ্ঞানের ডেটা বাড়িতে পাঠিয়েছিল। কিন্তু তার সোলার প্যানেল ঠিক দিকে মুখ করে ছিল না।" },
        end: { t: "আলো ফুরিয়ে গেল", d: "সূর্য আকাশে ঘুরতে ঘুরতে এমন জায়গায় গেল যে প্যানেলে আর আলো পড়ল না। প্রায় এক সপ্তাহ পরে Odysseus-এর বিদ্যুৎ শেষ হয়ে যায়।" },
        set: { t: "আসল সূর্যাস্ত", d: "এখানে সূর্য আসলে ডুবল এতদিনে। Odysseus আগেই আলো হারিয়েছিল হেলে থাকার কারণে, রাত নেমেছিল বলে নয়।" },
      },
      quiz: {
        q: "Odysseus হেলে পড়েছিল। এটা এত বড় সমস্যা হলো কেন?",
        a: ["তার সোলার প্যানেল ঠিকমতো সূর্যের দিকে থাকতে পারেনি", "রোবটের মাথা ঘোরে", "চাঁদ খুব পিচ্ছিল, দাঁড়ানো যায় না"],
        why: "বিদ্যুৎ বানাতে ল্যান্ডারের প্যানেলে রোদ পড়তে হয়। হেলে থাকায় Odysseus আসল সূর্যাস্তের কয়েক দিন আগেই আলো হারায়।",
      },
    },
    bg1: {
      tag: "পুরোপুরি সফল",
      what: "Blue Ghost ছিল প্রথম পুরোপুরি সফল বাণিজ্যিক চন্দ্র-অবতরণ। এটা পুরো এক চন্দ্র-দিন, প্রায় ১৪ পৃথিবী-দিন, আর রাতের শুরুতেও কয়েক ঘণ্টা কাজ করেছিল।",
      shows: "মডেল অনুযায়ী সাইটে সূর্য উঠেছিল অবতরণের কয়েক ঘণ্টা আগে আর ডুবেছিল ১৬ মার্চ ২০২৫-এর সন্ধ্যায়, ঠিক যে সন্ধ্যায় Blue Ghost তার শেষ ডেটা পাঠায়। মডেল আরও দেখায় ১৪ মার্চ সূর্য পুরোপুরি পৃথিবীর আড়ালে চলে গিয়েছিল; এটাই সেই গ্রহণ যার ছবি Blue Ghost তুলেছিল।",
      story: {
        rise: { t: "চাঁদে সূর্যোদয়", d: "নামার জায়গায় সূর্য সবে উঠেছে। Blue Ghost সকালে নামতে চায়, যাতে সামনে চাঁদের পুরো একটা দিনের রোদ পায়।" },
        land: { t: "অবতরণ!", d: "Blue Ghost চার পায়ে সোজা হয়ে নামল। সূর্য তাকে বিদ্যুৎ দিচ্ছে আর পৃথিবী আকাশে অনেক উপরে, তাই সে বাড়ির সাথে কথা বলতে পারে।" },
        eclipse: { t: "পৃথিবী সূর্যকে ঢেকে দিল", d: "কয়েক ঘণ্টার জন্য পৃথিবী সূর্যের সামনে চলে এল। চাঁদ থেকে এটা একটা সূর্যগ্রহণ, আর Blue Ghost তার ছবি তুলেছিল।" },
        set: { t: "সূর্য ডুবে গেল", d: "দুই সপ্তাহ দিনের আলোর পর রাত শুরু হলো। চাঁদের রাতও দুই সপ্তাহ লম্বা, আর পৃথিবীর যেকোনো জায়গার চেয়ে বেশি ঠান্ডা।" },
        end: { t: "শুভরাত্রি, Blue Ghost", d: "আরও কয়েক ঘণ্টা সে ব্যাটারিতে কাজ করে, তারপর চুপ হয়ে যায়। তার কাজ শেষ: পুরোপুরি সফল!" },
      },
      quiz: {
        q: "Blue Ghost একদম ঠিকঠাক কাজ করেছিল। তাহলে দুই সপ্তাহ পরে থেমে গেল কেন?",
        a: ["রকেটের জ্বালানি শেষ হয়ে গিয়েছিল", "সূর্য ডুবে গিয়ে লম্বা, ঠান্ডা রাত শুরু হয়েছিল", "সে পৃথিবীতে ফিরে এসেছিল"],
        why: "Blue Ghost চলত রোদে। দুই সপ্তাহের রাত শুরু হলে গরম থাকার মতো বিদ্যুৎ আর ছিল না। শুরু থেকেই পরিকল্পনা এমনই ছিল।",
      },
    },
    im2: {
      tag: "কাত হয়ে নেমেছে",
      what: "Athena আগের যেকোনো ল্যান্ডারের চেয়ে দক্ষিণ মেরুর কাছে নেমেছিল, Mons Mouton-এ লক্ষ্য থেকে প্রায় ২৫০ মিটার দূরে। এটা একটা ছোট গর্তের ভেতরে কাত হয়ে পড়ে, চার্জ নিতে পারেনি, আর পরের দিনই মিশন শেষ হয়ে যায়।",
      shows: "অবতরণের সময় সূর্য দিগন্তের মাত্র {sun}° উপরে ছিল। এত নিচু সূর্যকে গর্তের একটা দেয়ালই আড়াল করে দিতে পারে, আর গর্তের ভেতরে কাত হয়ে থাকা Athena-র চার্জ নেওয়ার কোনো উপায় ছিল না। এ কারণেই প্ল্যানার দিগন্তের প্রতিটা ডিগ্রি হিসাব করে।",
      story: {
        land: { t: "দক্ষিণ মেরুর সবচেয়ে কাছে", d: "Athena আগের যেকোনো ল্যান্ডারের চেয়ে চাঁদের দক্ষিণ মেরুর কাছে নামল। দেখো সূর্য কত নিচুতে: মাটি থেকে মাত্র {sun}° উপরে।" },
        side: { t: "গর্তের ভেতরে কাত হয়ে", d: "Athena একটা ছোট গর্তের ভেতরে কাত হয়ে পড়ে। সূর্য এত নিচুতে থাকায় গর্তের দেয়াল উঁচু বেড়ার মতো আলো আটকে দেয়।" },
        end: { t: "ব্যাটারি শেষ", d: "প্যানেলে রোদ না পড়ায় Athena চার্জ নিতে পারেনি। পরের দিনই মিশন শেষ হয়ে যায়।" },
      },
      quiz: {
        q: "Athena যেখানে নেমেছিল সেখানে সূর্য ছিল মাত্র {sun}° উপরে। এত নিচু সূর্যকে কী আড়াল করতে পারে?",
        a: ["মেঘ", "কিছুই না", "গর্তের দেয়াল, এমনকি ছোট একটা টিলাও"],
        why: "চাঁদে মেঘ নেই। কিন্তু মেরুর কাছে সূর্য এত নিচুতে থাকে যে মাটির যেকোনো উঁচু জায়গা তাকে ঢেকে দিতে পারে, তাই প্ল্যানাররা সব দিকের দিগন্ত দেখে নেয়।",
      },
    },
  },
  l3: {
    help: "কোনো সাইট বেছে তার আকাশ দেখো। বারটা সরিয়ে ৩০ দিন পর্যন্ত সামনে দেখো।",
    count: "টা সাইট ({m}টার মধ্যে) ল্যান্ডার চালাতে পারে", now: "এই মুহূর্তে", at: "{d} পরে",
    pick: "ল্যান্ডিং সাইট",
    skyAlt: "{site} থেকে আকাশ: সূর্য আর পৃথিবী দিগন্তের উপরে না নিচে।",
    below: "দিগন্তের নিচে", hill: "পাহাড়ের আড়ালে",
    sunOn: "রোদ আছে। সোলার প্যানেল চার্জ হচ্ছে।", sunOff: "রোদ নেই। ব্যাটারিতে চলছে।", sunBlocked: "সূর্য উঠেছে, কিন্তু পাহাড় বা গর্তের দেয়াল তাকে আড়াল করেছে।",
    sunEnds: "প্রায় {d} পরে রোদ চলে যাবে", sunBack: "প্রায় {d} পরে রোদ ফিরবে",
    earthOn: "পৃথিবী দেখা যাচ্ছে। রেডিও কাজ করছে।", earthOff: "পৃথিবী আড়ালে। বাড়ির সাথে যোগাযোগ নেই।",
    earthEnds: "প্রায় {d} পরে পৃথিবী ডুববে", earthBack: "প্রায় {d} পরে পৃথিবী উঠবে",
    noChange: "বাকি ৩০ দিন এভাবেই থাকবে",
    share: "এই ৩০ দিনে বিদ্যুৎ আর সংকেত একসাথে",
    details: "পুরো বিবরণ", plan: "এখানে নামার পরিকল্পনা করো",
    play: "৩০ দিন চালাও", pause: "থামাও", reset: "এখনে ফেরো", slider: "সময়, এখন থেকে ৩০ দিন সামনে পর্যন্ত",
    legSun: "রোদ", legEarth: "পৃথিবী দেখা যায়", end: "{d} পরে",
  },
  s2: {
    monthH: "০° এর উপরে মানে সাইট থেকে দেখা যায়।",
    movedNote: "NASA LOLA-র আসল ভূখণ্ড। প্রকাশিত বিন্দু থেকে {m} মিটার দূরে LOLA-র সবচেয়ে আলোকিত চূড়ায় বসানো (ভিন্ন ম্যাপে চূড়া একটু ভিন্ন জায়গায় পড়ে)।",
    yearT: "পরের ১২ মাস", yearH: "বছরের কত অংশে সূর্যের আলো, পৃথিবী, আর দুটোই।",
    eventsH: "পরের সূর্যোদয়, সূর্যাস্ত আর পৃথিবী-অস্ত (UTC)।",
  },
  g2: {
    intro: "চাঁদের দক্ষিণ মেরুর কাছে একটা ছোট ল্যান্ডার বাঁচিয়ে রাখো। সূর্য চার্জ দেয়, ঠান্ডা ব্যাটারি খরচ করে, আর পৃথিবী উপরে থাকলেই কেবল ডেটা পাঠানো যায়।",
    go: "চালিয়ে যাও",
    tip: {
      ok: "সব ঠিক আছে! সূর্য কখন ডুববে তা পূর্বাভাসে দেখে নাও।",
      send: "বিজ্ঞানের ডেটা পৃথিবীতে উড়ে যাচ্ছে!",
      sci: "ব্যাটারি ভালো আছে। বিজ্ঞানের যন্ত্র চালু করো!",
      radio: "পৃথিবী উঠেছে! রেডিও চালু করে ডেটা বাড়িতে পাঠাও।",
      full: "মেমরি ভরে গেছে। পৃথিবী ফেরা পর্যন্ত বিজ্ঞান বন্ধ রাখো।",
      dark: "অন্ধকার আর খুব ঠান্ডা। ব্যাটারি বাঁচাতে হাইবারনেট করো!",
      low: "ব্যাটারি কমে গেছে! কিছু বন্ধ করো বা হাইবারনেট করো।",
      sleep: "শ্‌শ্‌… সূর্য ফেরা পর্যন্ত বিদ্যুৎ বাঁচাচ্ছি।",
      wake: "অনেক রোদ! জেগে উঠে বিজ্ঞানের কাজ করো।",
      frozen: "ব্‌র্‌র্‌… ব্যাটারি শেষ হয়ে গেছে।",
    },
    bandHi: "তোমার ল্যান্ডারের সাথে পরিচিত হও",
    sndOn: "শব্দ চালু", sndOff: "শব্দ বন্ধ",
    share: "আমার স্কোর শেয়ার করো", copied: "কপি হয়েছে",
    shareText: "ছায়ার সাথে দৌড়, দৈনিক চ্যালেঞ্জ {day}: {mb} MB বাড়িতে পাঠানো {stars}",
    aiNote: "মিশনের ছবি, উপরের দৃশ্য আর লোডিং-এর ছবি এআই দিয়ে আঁকা, আসল ছবি নয়। গেম যা হিসাব করে তার সবই NASA JPL-এর আসল ডেটা থেকে।",
    x: {
      title: "দক্ষিণ মেরু এত কঠিন কেন?", sub: "নম্বর দেওয়া বিন্দুগুলোতে চাপ দিয়ে জেনে নাও।",
      alt: "চাঁদের দক্ষিণ মেরুর আঁকা ছবি: দিগন্তে সূর্য, কালো আকাশে নিচু হয়ে থাকা পৃথিবী, একটা উজ্জ্বল শৈলশিরা আর একটা গভীর অন্ধকার গর্ত।",
      sun: { t: "সূর্য নিচুতেই থাকে", d: "মেরুতে সূর্য কখনো উঁচুতে ওঠে না। সে দিগন্ত ঘেঁষে সরে যায়, তাই ছোট একটা টিলাও তাকে কয়েক দিন আড়াল করে রাখতে পারে।" },
      earth: { t: "পৃথিবীই একমাত্র ফোন লাইন", d: "ল্যান্ডার রেডিও দিয়ে বাড়ির সাথে কথা বলে। পৃথিবী দিগন্তের নিচে নেমে গেলে সে ফিরে না আসা পর্যন্ত বার্তা বন্ধ থাকে।" },
      ridge: { t: "উঁচু জায়গা বেশি আলো পায়", d: "শৈলশিরা আর গর্তের কিনারা রোদের মধ্যে উঁচু হয়ে থাকে। কিছু জায়গায় প্রায় সারা বছর আলো থাকে, যা সোলার প্যানেলের জন্য দারুণ।" },
      shadow: { t: "খুব লম্বা ছায়া", d: "সূর্য এত নিচুতে থাকায় ছোট একটা পাথরের ছায়াও তার চেয়ে অনেক লম্বা হয়। ছায়ায় আটকে পড়া ল্যান্ডার ব্যাটারি চার্জ করতে পারে না।" },
      crater: { t: "যে গর্ত কখনো সূর্য দেখে না", d: "কিছু গর্তের তলা কোটি কোটি বছর ধরে অন্ধকার। এগুলো আমাদের জানা সবচেয়ে ঠান্ডা জায়গাগুলোর মধ্যে পড়ে, আর সেখানে জমাট পানি লুকিয়ে থাকতে পারে।" },
    },
  },
  a: {
    title: "হাইফেন এআই-কে জিজ্ঞেস করো",
    intro: "হাইফেন এআই একটা রোবট গাইড, সে চাঁদের দক্ষিণ মেরু সম্পর্কে জানে। সূর্য, পৃথিবী, ল্যান্ডার বা কোথায় নামা ভালো, তাকে জিজ্ঞেস করো। আকাশের প্রশ্নে সে প্ল্যানারের মতোই NASA-র আসল ডেটা দেখে নেয়।",
    hello: "হাই, আমি হাইফেন এআই! চাঁদের দক্ষিণ মেরু নিয়ে তুমি কী জানতে চাও?",
    tryT: "কী জিজ্ঞেস করবে ভাবছ? একটা বেছে নাও:",
    qs: ["চাঁদের দক্ষিণ মেরুতে নামা এত কঠিন কেন?", "এই মুহূর্তে কোন কোন সাইটে রোদ আছে?", "আগামী মাসে নামার জন্য সবচেয়ে ভালো জায়গা কোনটা?",
         "Athena ল্যান্ডার কাজ করা বন্ধ করল কেন?", "চাঁদে একটা রাত কত লম্বা?", "ল্যান্ডারের পৃথিবীকে দেখতে পাওয়া দরকার কেন?"],
    close: "বন্ধ করো", tease: "হাই! চাঁদ নিয়ে আমাকে জিজ্ঞেস করো \ud83c\udf19",
    inputLabel: "তোমার প্রশ্ন", placeholder: "এখানে তোমার প্রশ্ন লেখো…", send: "জিজ্ঞেস করো", clear: "নতুন করে শুরু",
    thinking: "হাইফেন এআই আকাশ দেখছে…", checked: "হাইফেন এআই NASA-র আসল আকাশের ডেটা দেখে নিয়েছে",
    errSetup: "হাইফেন এআই এখনো চালু হয়নি। সাইট যিনি চালান তাঁকে একটা API key যোগ করতে হবে।",
    errOffline: "উত্তর দিতে হাইফেন এআই-এর ইন্টারনেট লাগে। সংযোগ দেখে আবার জিজ্ঞেস করো।",
    errBusy: "একসাথে অনেক প্রশ্ন! এক মিনিট অপেক্ষা করে আবার জিজ্ঞেস করো।",
    errRefused: "এই প্রশ্নে হাইফেন এআই সাহায্য করতে পারবে না। চাঁদ নিয়ে একটা প্রশ্ন করে দেখো!",
    errOther: "কিছু একটা ভুল হয়েছে। আবার জিজ্ঞেস করো।",
    note: "হাইফেন এআই একটা এআই, তার ভুল হতে পারে। সূর্য আর পৃথিবীর সংখ্যাগুলো সে প্ল্যানারের মতোই NASA JPL-এর ডেটা থেকে নেয়। তোমার নাম, স্কুল বা ঠিকানা এখানে লিখো না।",
  },
  g3: {
    howT: "কীভাবে খেলবে", howSub: "তুমি চাঁদের একটা ছোট ল্যান্ডারের মিশন কন্ট্রোল। চারটা জিনিস জেনে নাও:",
    steps: [["রোদে ব্যাটারি ভরে", "সূর্য উঠে থাকলে সোলার প্যানেল ব্যাটারি চার্জ করে। অন্ধকারে ঠান্ডা ব্যাটারি খরচ করে ফেলে।"],
            ["বিজ্ঞান ডেটা জমায়", "ডেটা সংগ্রহ করতে বিজ্ঞান চালু করো। এতে বিদ্যুৎ খরচ হয়, আর মেমরি ভরে যেতে পারে।"],
            ["রেডিও ডেটা বাড়িতে পাঠায়", "পৃথিবী উপরে থাকলে রেডিও চালু করো। পৃথিবীতে পৌঁছানো প্রতিটা MB তোমার স্কোরে যোগ হয়।"],
            ["অন্ধকারে হাইবারনেট করো", "সূর্য ডোবার আগে ব্যাটারি ভরে নাও। তারপর হাইবারনেট চেপে সূর্যোদয় পর্যন্ত ঘুমাও।"]],
    win: "মিশনের লক্ষ্য পূরণ করলে তুমি জিতবে।", lose: "ব্যাটারি ০% হয়ে গেলে হেরে যাবে।",
    keys: "প্রতিটা সতর্কবার্তায় গেম থেমে যায়, যাতে তুমি ভেবে সিদ্ধান্ত নিতে পারো। ছবির নিচের পূর্বাভাস দেখায় কখন সূর্য আর পৃথিবী উঠবে। ▶ ▶▶ ▶▶▶ দিয়ে গতি বদলাও, বা স্পেস বার চেপে থামাও।",
    goal: "তোমার লক্ষ্য", start: "মিশন শুরু করো", resume: "মিশনে ফেরো",
  },
  w: {
    title: "কেন কঠিন",
    help: "একই সূর্য, একই পৃথিবী। শুধু ল্যান্ডার কোথায় দাঁড়িয়ে আছে সেটা বদলায়। জায়গা বদলে চাঁদের একটা দিন দেখো।",
    canvasLabel: "চাঁদের দক্ষিণ মেরুতে একটা ল্যান্ডার, দিগন্ত ধরে সূর্য আর পৃথিবী চলছে",
    where: "ল্যান্ডার কোথায় দাঁড়িয়ে", ridge: "শৈলশিরার উপরে", crater: "গর্তের ভেতরে",
    pOn: "বিদ্যুৎ আছে", pOff: "বিদ্যুৎ নেই", rOn: "রেডিও চালু", rOff: "রেডিও নেই",
    msgBoth: "সূর্যের আলো আর পৃথিবী দুটোই আছে: ল্যান্ডার কাজ করতে পারবে।",
    msgNoSun: "সূর্য দিগন্তের পেছনে: বিদ্যুৎ নেই, ল্যান্ডার জমে যাচ্ছে।",
    msgNoEarth: "পৃথিবী দিগন্তের নিচে নেমে গেছে: রেডিও যোগাযোগ নেই।",
    msgNone: "সূর্যও নেই, পৃথিবীও নেই: ল্যান্ডারকে ঘুমিয়ে অপেক্ষা করতে হবে।",
    day: "চাঁদের দিন \u00b7 ৩০ এর মধ্যে {d} নম্বর দিন",
    tally: "এই চাঁদের দিন জুড়ে",
    tPower: "বিদ্যুৎ", tRadio: "রেডিও",
    note: "সামনের চাঁদের দিনের জন্য NASA JPL থেকে আসল সূর্য আর পৃথিবীর অবস্থান। দিগন্ত আনুমানিক; উচ্চতা \u00d7{k} বাড়িয়ে দেখানো।",
    photoT: "কক্ষপথ থেকে আসল দক্ষিণ মেরু",
    photoD: "এটা NASA-র Lunar Reconnaissance Orbiter-এর তোলা আসল ছবি। মাঝখানে মেরু। কালো জায়গাগুলো গর্তের তলা, যেখানে সূর্য কখনো পৌঁছায় না; উজ্জ্বল কিনারাগুলো বছরের বেশিরভাগ সময় আলো পায়। ঠিক এই পার্থক্য মাথায় রেখেই মিশন পরিকল্পনা করতে হয়।",
    photoPin: "শ্যাকলটন গর্ত (মেরু)",
    photoDark: "সবসময় ছায়ায়",
    photoCredit: "ছবি: NASA/GSFC/Arizona State University, LROC WAC দক্ষিণ মেরু মোজাইক",
  },
  p: {
    kicker: "NASA Space Apps 2026 · CLPS Lunar Mission Browser",
    question: 'চাঁদের দক্ষিণ মেরুতে কোথায় আর কবে নামলে ল্যান্ডার <b>বিদ্যুতের জন্য সূর্যের আলো</b> পাবে আর <em>যোগাযোগের জন্য পৃথিবী দেখতে পাবে</em>?',
    step1: "মেরুর মানচিত্রে একটা সাইট বেছে নাও", step2: "তারিখ বেছে নাও", step3: "রায় পড়ো আর Play চাপো",
    setup: "মিশন সাজাও",
    mapTitle: "দক্ষিণ মেরুর মানচিত্র",
    mapSub: "উপর থেকে মেরুর দিকে তাকিয়ে। প্রতিটা রিং ভরে ওঠে সেই সময়ের ভাগ দিয়ে যখন বিদ্যুৎ আর সিগন্যাল একসাথে থাকে।",
    mapEarth: "পৃথিবীর দিকে", mapSunNow: "এখন সূর্যের দিক",
    dropPin: "পিন বসাও", dropHint: "মানচিত্রে চাপলে সেখানে সাইট যোগ হবে", cancel: "বাতিল",
    offMap: "মানচিত্রের বাইরে",
    pickSite: "ল্যান্ডিং সাইট", pickDates: "তারিখ", startDate: "শুরুর তারিখ", howLong: "কত দিন",
    opt14: "২ সপ্তাহ", opt29: "চাঁদের ১ দিন (২৯.৫ দিন)", opt60: "২ মাস", opt180: "৬ মাস", opt365: "১ বছর",
    dateHint: "চাঁদের এক দিন প্রায় ২৯.৫ পৃথিবী-দিন। মেরুতে বছরের ঋতু অনুযায়ী আলোর পরিমাণও বদলায়।",
    advanced: "উন্নত সেটিংস", missionLen: "মিশন কত দিনের", missionHint: "নামার সেরা সময় বের করতে এটা লাগে।",
    maskLbl: "পৃথিবী অন্তত কত ডিগ্রি উপরে থাকতে হবে", maskHint: "অ্যান্টেনার জন্য অনেক সময় পৃথিবীকে দিগন্তের কয়েক ডিগ্রি উপরে থাকতে হয়। ০ মানে দিগন্তের ঠিক উপরে।",
    horizonLbl: "সাইটের চারপাশের জমির আকার", hSmooth: "মসৃণ চাঁদ (পাহাড় নেই)", hRaised: "পাহাড়ের উপর সাইট (উচ্চতা দাও)", hTerrain: "NASA LOLA-র আসল ভূখণ্ড (ফাইল লোড করো)",
    metres: "মিটার, সমতলের চেয়ে উঁচু", loadCsv: "ভূখণ্ডের ফাইল লোড করো (horizon_mask.py থেকে CSV)",
    csvBad: "ফাইল থেকে দিগন্ত পড়া গেল না। প্রতি লাইনে azimuth_deg,horizon_deg থাকার কথা।",
    csvFar: "লোড হয়েছে, কিন্তু ফাইলটা {lat}, {lon} এর জন্য বানানো, {site} এর জন্য না।",
    addSite: "স্থানাঙ্ক দিয়ে সাইট যোগ করো", latlonHint: "অক্ষাংশ, দ্রাঘিমাংশ ডিগ্রিতে। দক্ষিণ আর পশ্চিম হলে মাইনাস।", addBtn: "সাইট যোগ করো", custom: "আমার সাইট",
    ground: "মাটি আর পাহাড়", sky: "আকাশ",
    skyTitle: "ওখানে দাঁড়ালে যা দেখতে",
    skySub: "তোমার চারপাশে পুরো এক চক্কর, উত্তর থেকে আবার উত্তর পর্যন্ত। ধূসর অংশটা মাটি; এর উপরে যা আছে তা দেখা যায়। হালকা বিন্দুগুলো পুরো সময়ে সূর্য আর পৃথিবীর পথ দেখায়।",
    hSmoothS: "মসৃণ চাঁদ", hRaisedS: "{h} মিটার উঁচু পাহাড়ে", hTerrainS: "আসল ভূখণ্ড",
    play: "চালাও", pause: "থামাও", speed: "গতি", time: "সময়",
    sunUp: "সূর্য উঠে আছে", sunUpN: "সোলার প্যানেল চার্জ হচ্ছে", sunPart: "সূর্য আংশিক ঢাকা", sunPartN: "সূর্যের {p}% দেখা যাচ্ছে", sunDown: "সূর্য ডুবে আছে", sunDownN: "ব্যাটারিতে চলছে",
    earthUp: "পৃথিবী দেখা যাচ্ছে", earthUpN: "বাড়িতে ডেটা পাঠানো যাবে", earthDown: "পৃথিবী আড়ালে", earthDownN: "পৃথিবীর সাথে কোনো সিগন্যাল নেই",
    tlTitle: "পুরো সময় জুড়ে",
    tlSub: "লাইন শূন্যের উপরে মানে সূর্য বা পৃথিবী দেখা যাচ্ছে। নিচের বারগুলো দেখায় কখন বিদ্যুৎ, কখন সিগন্যাল, আর কখন দুটোই আছে। সময় বদলাতে চাপো বা টেনে নাও।",
    yAxis: "দিগন্ত থেকে কত ডিগ্রি উপরে", bPower: "বিদ্যুৎ", bSignal: "সিগন্যাল", bBoth: "দুটোই",
    cmpTitle: "ল্যান্ডিং সাইট তুলনা", cmpSub: "সব সাইটের জন্য একই তারিখ। কোনো সারিতে চাপলে সেটা খুলবে, শিরোনামে চাপলে সাজানো হবে।",
    cSite: "সাইট", cSun: "সূর্যের আলো", cDark: "লম্বা অন্ধকার", cEarth: "পৃথিবী দেখা যায়", cBoth: "দুটোই", cPub: "প্রকাশিত",
    pubHint: '“প্রকাশিত” হলো আসল পাহাড়-পর্বত ধরে করা গবেষণায় পাওয়া দীর্ঘমেয়াদি আলোর হিসাব (<a href="https://en.wikipedia.org/wiki/Peak_of_eternal_light" target="_blank" rel="noopener">সারাংশ</a>)। আমাদের মসৃণ-চাঁদের সংখ্যার সাথে বড় পার্থক্য দেখায় ভূখণ্ড কতটা গুরুত্বপূর্ণ।',
    winTitle: "নামার সেরা সময়",
    winSub: "{site}-এ {n} দিনের মিশনের জন্য। % যত বেশি, বিদ্যুৎ আর সিগন্যাল একসাথে তত বেশি সময় পাওয়া যাবে।",
    winWorst: "দুটো একসাথে না থাকার সবচেয়ে লম্বা সময়: {d}", winSc: "বিদ্যুৎ + সিগন্যাল",
    winNone: "এই তারিখগুলোতে এখানে সূর্য আর পৃথিবী একসাথে থাকে এমন কোনো সময় নেই। লম্বা সময়, অন্য সাইট, বা উন্নত সেটিংসে পৃথিবীর উচ্চতা কমিয়ে দেখো।",
    kSun: "সূর্যের আলো (বিদ্যুৎ)", kSunN: "সময়", kDark: "সবচেয়ে লম্বা অন্ধকার", kDarkN0: "সূর্য ডোবে না", kDarkN: "একটানা",
    kEarth: "পৃথিবী দেখা যায় (সিগন্যাল)", kEarthN: "সময়", kBoth: "বিদ্যুৎ আর সিগন্যাল একসাথে", kBothN: "সময়",
    vGreat: "নামার জন্য ভালো জায়গা", vOk: "সম্ভব, তবে পরিকল্পনা লাগবে", vHard: "টিকে থাকা কঠিন",
    vHeadGreat: "এই তারিখগুলোতে {site} ভালো", vHeadOk: "{site} চলবে, তবে বিরতির জন্য প্রস্তুত থাকতে হবে", vHeadHard: "এই তারিখগুলোতে {site} কঠিন",
    vSunAll: "এই সময়ে এখানে সূর্য একবারও ডোবে না, তাই সোলার প্যানেল সবসময় আলো পায়।",
    vSun: "সূর্য {p}% সময় দেখা যায়। সবচেয়ে লম্বা অন্ধকার সময় {d}।",
    vEarthAll: "পৃথিবী সবসময় দেখা যায়, তাই ল্যান্ডার সবসময় বাড়িতে ডেটা পাঠাতে পারবে।",
    vEarthNone: "এই সময়ে এখানে পৃথিবী একবারও ওঠে না, তাই সরাসরি যোগাযোগ সম্ভব না। রিলে স্যাটেলাইট লাগবে।",
    vEarth: "পৃথিবী {p}% সময় দেখা যায়, অর্থাৎ ততটা সময় ল্যান্ডার যোগাযোগ করতে পারবে। সবচেয়ে লম্বা নীরবতা {d}।",
    vWarn: "সতর্কতা: বেশিরভাগ ছোট ল্যান্ডার কয়েক দিনের বেশি অন্ধকারে টিকতে পারে না। ঠান্ডায় ব্যাটারি শেষ হয়ে যায়।",
    vTerrain: "এখানে পাহাড়হীন মসৃণ চাঁদ ধরা হয়েছে। সাইটভিত্তিক সঠিক উত্তরের জন্য উন্নত সেটিংসে আসল ভূখণ্ড লোড করো।",
    glossTitle: "এখানে ব্যবহৃত শব্দ",
    gloss: [["দিগন্ত (Horizon)", "যেখানে মাটি আর আকাশ মেলে। পাহাড় আর গর্তের কিনারার কারণে কোনো দিকে এটা উঁচু হয়।"],
            ["উচ্চতা কোণ (Elevation)", "সমতল দিগন্ত থেকে কোনো কিছু কত ডিগ্রি উপরে। ০° মানে ঠিক দিগন্তে, ৯০° মানে মাথার উপরে।"],
            ["সরাসরি পৃথিবী-যোগাযোগ", "ল্যান্ডার রেডিওতে পৃথিবীর সাথে কথা বলে। পৃথিবী দিগন্তের উপরে থাকলেই কেবল এটা কাজ করে।"],
            ["চাঁদের দিন", "এক সূর্যোদয় থেকে পরের সূর্যোদয় প্রায় ২৯.৫ পৃথিবী-দিন। মেরু থেকে দূরে এটা মোটামুটি ২ সপ্তাহ আলো আর ২ সপ্তাহ রাত।"],
            ["মেরু কেন আলাদা", "চাঁদের অক্ষ মাত্র ১.৫° হেলানো, তাই মেরুতে সূর্য উপরে না উঠে দিগন্তের চারপাশে ঘোরে।"],
            ["লিব্রেশন (Libration)", "ঘোরার সময় চাঁদ হালকা দোলে, তাই মেরু থেকে পৃথিবী ধীরে ধীরে দিগন্তের উপরে-নিচে ওঠানামা করে।"],
            ["LOLA", "NASA-র Lunar Reconnaissance Orbiter-এর লেজার যন্ত্র, যেটা পুরো চাঁদের উচ্চতার ম্যাপ বানিয়েছে।"],
            ["CLPS", "Commercial Lunar Payload Services: NASA প্রাইভেট কোম্পানিকে টাকা দেয় যাতে তাদের ল্যান্ডারে বিজ্ঞানের যন্ত্র চাঁদে যায়।"]],
    howTitle: "সংখ্যাগুলো কীভাবে হিসাব করা",
    notes: ["<b>সূর্য আর পৃথিবী কোথায়।</b> NASA JPL-এর DE421 ephemeris থেকে, চাঁদের দোলন (librations) সহ, NASA-র LOLA ম্যাপের চাঁদ-ভিত্তিক ফ্রেমে রূপান্তর করা। আলোর যাত্রার সময় আর চাঁদের কেন্দ্র থেকে সাইটের দূরত্বও ধরা হয়েছে। ডেটা ২০২৪–২০৩২, প্রতি ৩ ঘণ্টায়। চাঁদের অবস্থান আলাদা IAU মডেলের সাথে ১৫ আর্কসেকেন্ডের মধ্যে মেলে।",
            "<b>বিদ্যুৎ।</b> সূর্যের চাকতির অন্তত অর্ধেক দিগন্তের উপরে থাকলে গোনা হয়।",
            "<b>সিগন্যাল।</b> পৃথিবীর কেন্দ্র দিগন্ত আর উন্নত সেটিংসের ন্যূনতম উচ্চতার উপরে থাকলে গোনা হয়।",
            "<b>জমির আকার।</b> মসৃণ চাঁদ মানে নিখুঁত গোলক। পাহাড়ের উপর সাইট হলে দিগন্ত একটু নিচে নামে। আসল ভূখণ্ড আসে NASA LOLA উচ্চতার ম্যাপ থেকে, সাথের Python টুল দিয়ে। কেবল আসল ভূখণ্ডই গর্তের কিনারার ছায়া ধরতে পারে।",
            "<b>নামার সেরা সময়।</b> বাছাই করা তারিখে প্রতি ৬ ঘণ্টা পরপর নামার সময় হিসেবে পরীক্ষা করা হয়। স্কোর হলো মিশনের কত অংশে বিদ্যুৎ আর সিগন্যাল একসাথে আছে; সমান হলে যেটায় সবচেয়ে লম্বা বিরতি কম সেটা আগে। নামার মুহূর্তে সূর্য আর পৃথিবী দুটোই থাকতে হবে।",
            "<b>সীমাবদ্ধতা।</b> সাইটের স্থানাঙ্ক প্রকাশিত গবেষণা থেকে, আনুমানিক। রিলে স্যাটেলাইট, গ্রাউন্ড স্টেশনের সময়সূচি, তাপমাত্রা আর ঢালের নিরাপত্তা ধরা হয়নি।"],
    gameCta: "ছায়ার সাথে দৌড় খেলো", gameCtaSub: "একই আকাশের ডেটায় চন্দ্র-রাত পার করে ল্যান্ডার বাঁচিয়ে রাখো।",
  },

  g: {
    tagline: "NASA JPL-এর আসল আকাশের ডেটায় চলা চাঁদে টিকে থাকার গেম",
    intro: "তুমি চাঁদের দক্ষিণ মেরুর কাছে একটা ছোট রোবট ল্যান্ডার চালাচ্ছ। <b>সূর্য ব্যাটারি চার্জ করে, ঠান্ডা ব্যাটারি খরচ করে, আর পৃথিবী দিগন্তের উপরে থাকলেই কেবল ডেটা বাড়িতে পাঠানো যায়।</b> এই গেমের প্রতিটা সূর্যোদয়, সূর্যাস্ত আর পৃথিবী-অস্ত NASA JPL-এর আসল ডেটা থেকে, তুমি যে তারিখে খেলছ সেই তারিখের।",
    scn: {
      vikram: { t: "বিক্রমের রাত", d: "কঠিন", story: "২০২৩ সালে ভারতের বিক্রম ল্যান্ডার ৬৯° দক্ষিণের কাছে নেমে বিজ্ঞানের কাজ করে, কিন্তু প্রথম চন্দ্র-রাতের পর আর জাগেনি। তোমার ল্যান্ডারে টিকে থাকার হিটার আছে। অন্ধকার পার হতে পারবে?", goal: "২ সপ্তাহের রাত পার হয়ে সূর্যোদয়ে জেগে ওঠো।" },
      tipped: { t: "কাত হয়ে পড়া", d: "মাঝারি", story: "২০২৫ সালে একটা ল্যান্ডার কাত হয়ে নেমেছিল, আর সোলার প্যানেল ভুল দিকে মুখ করে ছিল। তোমারটা Malapert পাহাড়ে বাঁকা হয়ে নেমেছে। প্যানেল কেবল এক দিক থেকে সূর্য ধরতে পারে।", goal: "১০ দিনে {g} MB বিজ্ঞানের ডেটা পাঠাও।" },
      peak: { t: "আলোর চূড়া", d: "মুক্ত", story: "তুমিই মিশন প্ল্যানার। দক্ষিণ মেরুর কোনো শৈলশিরায় সাইট আর আগামী এক বছরের যেকোনো তারিখ বেছে নাও, তারপর ১৪ দিনের মিশন চালাও।", goal: "১৪ দিনে যত বেশি সম্ভব ডেটা পাঠাও।" },
      daily: { t: "আজকের চ্যালেঞ্জ", d: "দৈনিক", story: "প্রতিদিন একটা নতুন মিশন, সবার জন্য একই: দশ দিন, ক্যালেন্ডার থেকে বাছা একটা সাইট আর একটা তারিখ। বন্ধুদের স্কোর ছাড়িয়ে যাও।", goal: "১০ দিনে যত বেশি সম্ভব ডেটা পাঠাও।" },
    },
    best: "তোমার সেরা: {v}", play: "খেলো",
    setupTitle: "কোথায় আর কবে নামবে বেছে নাও", setupSub: "আসল প্ল্যানাররা ঠিক এটাই করে। নিচের পূর্বাভাস তোমার বাছাইয়ের জন্য পরের ১৪ দিনের আলো আর পৃথিবী-যোগাযোগ দেখায়।",
    site: "ল্যান্ডিং সাইট", landDate: "নামার তারিখ (০০:০০ UTC)", back: "পেছনে", launch: "এখানে নামো",
    pvTxt: "পরের ১৪ দিন: সূর্য {s}% সময়, পৃথিবী {e}% সময়, দুটো একসাথে {b}% সময়।",
    abort: "মিশন ছাড়ো", battery: "ব্যাটারি", stored: "পাঠানোর অপেক্ষায়", sent: "পৃথিবীতে পাঠানো", clock: "মিশনের সময়",
    fcTitle: "পূর্বাভাস: পরের ৫ দিন", fcSub: "আসল ephemeris থেকে", now: "এখন", dayN: "+{n}দি",
    sci: "বিজ্ঞানের যন্ত্র", rad: "পৃথিবীতে রেডিও", hib: "হাইবারনেট", on: "চালু", off: "বন্ধ",
    sciS: "+{mb} MB/ঘণ্টা · {w} W খরচ", radS: "{mb} MB/ঘণ্টা · {w} W · পৃথিবী উপরে থাকতে হবে", hibS: "মাত্র {w} W খরচ। বিজ্ঞান আর রেডিও বন্ধ।",
    radWait: "অপেক্ষা: পৃথিবী দিগন্তের নিচে", radIdle: "পাঠানোর মতো কিছু নেই",
    autoPause: "সতর্কবার্তায় থামো", logTitle: "মিশন লগ", pauseLbl: "থামাও", spaceHint: "স্পেস বার চাপলে থামে আর চলে",
    flowIn: "সোলার আসছে", flowOut: "খরচ হচ্ছে", maxMb: "সর্বোচ্চ {n} MB",
    day: "দিন {d}", dayShort: "দিন {d} · {h}:00",
    goal: "লক্ষ্য", goalPeak: "১৪ দিনে যত বেশি সম্ভব পাঠাও",
    exag: "উচ্চতা ×{k} বাড়িয়ে দেখানো", panel: "প্যানেল",
    ev: {
      land: "অবতরণ! সব সিস্টেম চালু।",
      sunsetSoon: "প্রায় {h} ঘণ্টা পর সূর্যাস্ত। ব্যাটারি কি পুরো ভরা?",
      sunset: "সূর্য ডুবে গেছে। হিটার চালু।",
      sunrise: "সূর্যোদয়! প্যানেল আবার চার্জ হচ্ছে।",
      earthsetSoon: "প্রায় {h} ঘণ্টা পর পৃথিবী ডুববে। এখনই ডেটা পাঠাও।",
      earthset: "পৃথিবী ডুবে গেছে। রেডিও যোগাযোগ নেই।",
      earthrise: "পৃথিবী আবার দিগন্তের উপরে।",
      batLow: "ব্যাটারি ২৫% এর নিচে। খরচ কমাও বা হাইবারনেট করো।",
      storeFull: "মেমরি ভরা। নতুন ডেটা হারিয়ে যাচ্ছে।",
      frozen: "ব্যাটারি শেষ। ল্যান্ডার জমে গেছে।",
      done: "মিশন শেষ।", hib: "হাইবারনেট করছে। শুধু টিকে থাকার হিটার চালু।", wake: "জেগে উঠছে। সিস্টেম আবার চালু।",
    },
    win: "মিশন সফল", lose: "ল্যান্ডার হারিয়ে গেছে", done: "মিশন শেষ",
    st: { sent: "পৃথিবীতে পাঠানো", lost: "হারানো ডেটা (মেমরি ভরা)", minBat: "সবচেয়ে কম ব্যাটারি", dark: "অন্ধকারে কাটানো ঘণ্টা", survived: "টিকে ছিল", hours: "{n} ঘণ্টা" },
    replayCap: "মিশন জুড়ে ব্যাটারি (হলুদ = সূর্য উপরে, নীল = পৃথিবী উপরে)।",
    again: "আবার চেষ্টা করো", other: "অন্য মিশন",
    why: {
      title: "কেন এমন হলো?",
      vikramWin: "তুমি <b>{b}%</b> ব্যাটারি নিয়ে রাতে ঢুকে হাইবারনেট করেছ। {w} W খরচে <b>{n} ঘণ্টার</b> অন্ধকার পার হতে টিকে থাকার হিটারের প্রায় <b>{need} Wh</b> লেগেছে।",
      vikramLose: "এই সাইটে রাত ছিল <b>{n} ঘণ্টা</b>। জেগে থাকলে অন্ধকারে ল্যান্ডার {aw} W খরচ করে, তাই পুরো ব্যাটারিও মাত্র প্রায় <b>{last} ঘণ্টা</b> চলে। হাইবারনেট করলেও প্রায় {need} Wh লাগে, তাই রাত শুরুর সময় ব্যাটারি প্রায় ভরা থাকতে হবে।",
      vikramFact: "আসল বিক্রম ল্যান্ডার বানানো হয়েছিল এক চন্দ্র-দিনের জন্য, প্রায় ১৪ পৃথিবী-দিন, আর রাতের পর আর জাগেনি। চন্দ্র-রাতে টিকে থাকা চাঁদের ল্যান্ডারের সবচেয়ে কঠিন সমস্যাগুলোর একটা।",
      tippedTxt: "তোমার প্যানেল {pa}° দিকে মুখ করা ছিল। মেরুর কাছে সূর্য প্রায় ২৯.৫ দিনে পুরো দিগন্ত এক চক্কর ঘোরে, তাই মিশনের একটা অংশে সূর্য প্যানেলের পেছনে ছিল। সূর্য যখন প্যানেলের দিকে ঘুরে এসেছে, তখনই বেশি বিদ্যুৎ পেয়েছ।",
      tippedLose: "প্যানেলে প্রায় কোনো আলো না থাকা অবস্থায় ল্যান্ডার সব চালু রেখেছিল, তাই ব্যাটারি শেষ হয়ে গেছে। প্রথমে হাইবারনেট করো, আর সূর্য প্যানেলের দিকে ঘুরে এলে বিজ্ঞান চালু করো।",
      tippedFact: "ল্যান্ডার কাত হয়ে পড়লে সোলার প্যানেল মাটির দিকে বা ভুল দিকে মুখ করে থাকতে পারে, আর ব্যাটারি চার্জ না হওয়ায় মিশন আগেই শেষ হয়ে যেতে পারে।",
      peakTxt: "{site}-এ তোমার মিশনের {s}% সময় সূর্য আর {e}% সময় পৃথিবী উপরে ছিল, দুটো একসাথে {b}%। গর্তের কিনারা আর শৈলশিরার উঁচু জায়গা বেশি আলো পায়; পৃথিবী-যোগাযোগ নির্ভর করে চাঁদের ধীর দোলনের উপর।",
      peakFact: "একই সাইট অন্য তারিখে চেষ্টা করো, বা প্ল্যানারে সব সাইট একসাথে তুলনা করো।",
      data: "সূর্য আর পৃথিবীর সব অবস্থান তোমার তারিখের জন্য NASA JPL-এর DE421 ephemeris থেকে নেওয়া। চাঁদকে মসৃণ ধরা হয়েছে (পাহাড় নেই), তাই আসল কিনারার সাইট আরও ভালো করতে পারে।",
      open: "এই সাইট প্ল্যানারে খোলো",
    },
  },
  adv: {
    kicker: "নভোচারী প্রশিক্ষণ",
    title: "চলো <em>চাঁদে</em> যাই!",
    intro: "তোমার নভোচারী বেছে নাও, স্পেসস্যুট পরো, রকেট বাছো, তারপর পৃথিবী থেকে উড়ে যাও চাঁদের দক্ষিণ মেরুতে।",
    mc: "মিশন কন্ট্রোল",
    you: "কমান্ডার {name}",
    step: "ধাপ {n} / {total}",
    nameQ: "মিশন কন্ট্রোল তোমাকে কী নামে ডাকবে?",
    namePh: "তোমার ডাকনাম বা নামের প্রথম অংশ",
    nameNote: "শুধু ডাকনাম বা নামের প্রথম অংশ দাও। এটা এই ডিভাইসেই থাকে, কোথাও পাঠানো হয় না।",
    kidQ: "কে চাঁদে যাচ্ছে?",
    suitQ: "তোমার স্পেসস্যুট বাছো",
    shipQ: "তোমার রকেট বাছো",
    avatar: "নভোচারী {n}",
    suits: { white: "ক্লাসিক সাদা", orange: "উদ্ধার কমলা", blue: "ভবিষ্যতের নীল" },
    suitsD: { white: "মহাকাশে হাঁটার সময় নভোচারীরা যেমন স্যুট পরেন।", orange: "উজ্জ্বল কমলা রং দূর থেকেও সহজে চোখে পড়ে।", blue: "আগামী দিনের অভিযাত্রীদের জন্য ঝলমলে বর্ম।" },
    ships: { rocket: "লাল ধূমকেতু", shuttle: "স্টার শাটল", future: "নীল তীর" },
    shipsD: { rocket: "তিনটে গোল জানালাওয়ালা ক্লাসিক রকেট।", shuttle: "বিশাল জ্বালানি ট্যাংকে চড়া একটা মহাকাশ-বিমান।", future: "ভবিষ্যতের ঝকঝকে রকেট।" },
    next: "পরের ধাপ", back: "পেছনে", go: "মিশন শুরু করো!", ok: "ঠিক আছে!",
    suitUp: "স্যুট পরা হচ্ছে…",
    voice: "জোরে পড়ে শোনাও", sound: "শব্দ", skip: "বাদ দাও", lang: "ভাষা",
    noVoice: "এই ডিভাইসে বাংলা কণ্ঠ নেই, তাই মিশন কন্ট্রোল শুধু লেখা দেখাবে। Microsoft Edge বা Android-এর Chrome-এ বাংলা কণ্ঠ শোনা যায়।",
    hold: "চেপে ধরো", fire: "চালু করো", drop: "ফেলে দাও", brake: "ব্রেক", thrust: "থ্রাস্ট", photo: "ছবি তোলো", jump: "লাফ দাও", plant: "পতাকা পোঁতো",
    alt: "উচ্চতা", speed: "গতি", kmh: "{n} কিমি/ঘণ্টা", ms: "{n} মি/সে", m: "{n} মি", km: "{n} কিমি",
    toMoon: "চাঁদ পর্যন্ত", day: "দিন {n}",
    found: "{n} / {total}",
    b: {
      hello: "হ্যালো, ভবিষ্যতের নভোচারী! আমি মিশন কন্ট্রোল। চাঁদ পর্যন্ত পুরো পথ আমি তোমার সাথে থাকব। প্রথমে বলো, তোমার নাম কী?",
      kid: "তোমার সাথে পরিচয় হয়ে ভালো লাগল, {name}! যে নভোচারী এই অভিযানে যাবে, তাকে ছোঁও।",
      suit: "মহাকাশে বাতাস নেই, রোদে ভীষণ গরম আর ছায়ায় ভীষণ ঠান্ডা। তোমার স্যুট তোমাকে নিরাপদ রাখবে। একটা বেছে নাও!",
      ship: "এবার রকেট বাছো! পৃথিবীর টান ছাড়াতে রকেটকে প্রতি সেকেন্ডে ১১ কিলোমিটার যেতে হয়।",
      ready: "দল তৈরি! কমান্ডার {name}, চাঁদে উড়ে যেতে তুমি তৈরি তো?",
      pad: "তুমি লঞ্চ প্যাডে! ইঞ্জিন চালু করতে বড় বোতামটা চেপে ধরে রাখো।",
      holdOn: "ধরে রাখো… ইঞ্জিন গরম হচ্ছে!",
      liftoff: "উড়ান শুরু! শক্ত করে ধরো, খুব কাঁপছে!",
      sky: "আকাশ অন্ধকার হয়ে আসছে। এত উঁচুতে বাতাস খুব কম।",
      stage: "প্রথম জ্বালানি ট্যাংক খালি! রকেট হালকা করতে 'ফেলে দাও' ছোঁও।",
      orbit: "আমরা কক্ষপথে! মাত্র ৯০ মিনিটে আমরা পুরো পৃথিবী একবার ঘুরে আসি। চারপাশ দেখতে স্ক্রিন টেনে ঘোরাও!",
      tli: "চাঁদ ৩,৮৪,০০০ কিলোমিটার দূরে। চাঁদের দিকে যেতে 'চালু করো' ছোঁও!",
      water: "ওজনহীনতা! এখানে পানি গোল গোল বলের মতো ভাসে। পানির বলগুলো ছুঁয়ে পান করো!",
      waterDone: "চুমুক! নভোচারীরা সত্যিই এভাবে পানি খান।",
      rocks: "ওহ না, সামনে মহাকাশের পাথর! ছুঁয়ে ছুঁয়ে সরিয়ে দাও!",
      rocksDone: "উফ! দারুণ চালিয়েছ, {name}!",
      gaze: "{name} ভেসে ভেসে জানালার কাছে গিয়ে কাচে নাক ঠেকিয়ে বাইরে তাকাল…",
      galaxy: "বাহ! তারার ওই উজ্জ্বল নদীটাই আমাদের ছায়াপথ, মিল্কিওয়ে। এতে ১০ হাজার কোটিরও বেশি তারা আছে, আর আমাদের সূর্য তার মধ্যে মাত্র একটা!",
      lookBack: "পেছনে তাকাও! পৃথিবী ছোট থেকে ছোট হচ্ছে। চাঁদে যেতে প্রায় ৩ দিন লাগে।",
      wave: "পৃথিবীকে বিদায় জানাতে পৃথিবীটা ছোঁও!",
      waved: "টাটা, পৃথিবী! শীঘ্রই দেখা হবে!",
      brake: "আমরা চাঁদে পৌঁছে গেছি! গতি কমাতে 'ব্রেক' চেপে ধরো, যাতে চাঁদের টান আমাদের ধরে ফেলে।",
      earthrise: "বাহ, দেখো! চাঁদের দিগন্তে পৃথিবী উঠছে। ছবি তুলতে 'ছবি তোলো' ছোঁও!",
      photo: "দারুণ ছবি! এটা তোমার সার্টিফিকেটে থাকবে।",
      lander: "এবার নামার পালা! ল্যান্ডার রকেট থেকে আলাদা হচ্ছে। এখন তুমিই চালাবে!",
      landHow: "চাঁদ তোমাকে নিচে টানছে। গতি কমাতে 'থ্রাস্ট' চেপে ধরো, আর আস্তে নামো!",
      tooFast: "খুব জোরে! 'থ্রাস্ট' চেপে ধরো!",
      bumpy: "একটু ঝাঁকুনি লাগল, কিন্তু সবাই ঠিক আছে! উফ!",
      touchdown: "অবতরণ! তুমি চাঁদের দক্ষিণ মেরুর কাছে নেমেছ! একদম আলতো করে!",
      pole: "এখানে, {site}-এ, সূর্য দিগন্তের কাছে নিচু থাকে, তাই ছায়া খুব লম্বা হয়। যে অন্ধকার গর্তে কখনো রোদ পড়ে না, সেখানে বরফ লুকিয়ে আছে!",
      live: "তোমার আকাশে সূর্য আর পৃথিবী ঠিক সেখানেই আছে, যেখানে এই মুহূর্তে এই জায়গা থেকে সত্যিই দেখা যায়।",
      walk: "চাঁদে হাঁটার সময়! 'লাফ দাও' ছোঁও। চাঁদে তোমার ওজন ৬ গুণ কম, তাই অনেক উঁচুতে লাফাতে পারবে!",
      jumped: "ওয়াও! কী দারুণ লাফ!",
      flag: "চাঁদে পোঁতার জন্য একটা পতাকা বাছো।",
      plantHow: "চাঁদের ধুলোয় খুঁটি পুঁততে 'পতাকা পোঁতো' ছোঁও!",
      noWind: "চাঁদে বাতাস নেই, তাই চাঁদের আসল পতাকার ওপরে একটা রড থাকে, যাতে পতাকা খোলা থাকে!",
      peace: "চাঁদ কারো একার নয়, সবার। তাই আমরা সব মানুষের জন্য একটা বার্তা রেখে যাব।",
      done: "মিশন সম্পূর্ণ, কমান্ডার {name}! স্যালুট!",
    },
    flagQ: "তোমার পতাকা বাছো", flagSearch: "দেশ খোঁজো", flagNone: "কোনো দেশ পাওয়া যায়নি",
    plaque: "এখানে পৃথিবী গ্রহের {name} চাঁদের দক্ষিণ মেরুর কাছে পা রেখেছিল। আমরা এসেছিলাম শান্তিতে, সব মানুষের জন্য।",
    cert: {
      title: "চাঁদে অবতরণের সার্টিফিকেট", line: "এই মর্মে জানানো হচ্ছে যে", did: "পৃথিবী থেকে চাঁদে উড়ে গিয়ে চাঁদের দক্ষিণ মেরুর কাছে অবতরণ করেছে।",
      date: "তারিখ", ship: "রকেট", site: "অবতরণের জায়গা", signed: "মিশন কন্ট্রোল",
      download: "সার্টিফিকেট ডাউনলোড করো", again: "আবার ওড়ো", home: "হাইফেনে ফিরে যাও", game: "এরপর: 'ছায়ার সাথে দৌড়'-এ ল্যান্ডারকে বাঁচিয়ে রাখো",
    },
    lite: "তোমার ডিভাইস ব্যস্ত, তাই সহজ ৩ডি চালু করা হলো।",
    no3d: "এই ডিভাইসে মিশনের ৩ডি অংশ দেখানো যাচ্ছে না। অন্য ব্রাউজার বা কম্পিউটারে চেষ্টা করো।",
  },
};

export type Lang = "en" | "bn" | "es";
export const LANGS: Lang[] = ["en", "bn", "es"];
/** A language may leave keys out; lookups fall back to English. */
export const DICT: Record<Lang, object> = { en, bn, es };
